// txdot-letting-monthly — monthly Socrata → R2 ingest dispatch.
// Cron: 1st of month, 08:00 UTC. POSTs the Modal-issued stable Web Function URL
// for data-engine-x-txdot-letting-ingest::trigger_ingest_via_http, which calls
// ingest_socrata_to_r2.spawn(...) and returns the Modal call_id.
//
// Auth: Modal Web Functions are public to the internet (per Modal docs); the
// upstream Socrata source is also public, so no per-request secret is required.
// If we ever need to gate this endpoint, add a shared-secret header check
// inside trigger_ingest_via_http and read the corresponding secret from Doppler
// via a Modal Secret.
//
// Web Function URL stability: the URL `https://bencrane--<app>-<fn>-<hash>.modal.run`
// is generated by Modal at deploy time and persists as long as the function name
// + app name + workspace don't change. If we ever rename the function or app,
// re-deploy + update this URL.
//
// Replaced the audit-proposed `api.modal.com/v1/spawn/{app}/{fn}` URL after the
// 2026-05-18 cycle verified that endpoint is non-existent (returns HTTP 200
// with empty body — the cron would have silently no-op'd on first fire).
// Verified working: 2026-05-18T06:30Z probe returned
// {"call_id":"fc-01KRWWCKN6W0YNXWEG73BCDTVH","snapshot_date":"2026-05-18"}.

import { logger, schedules } from "@trigger.dev/sdk/v3";

import { passesGate, SKIPPED_DISABLED } from "./lib/scheduled-gate";

const MODAL_TRIGGER_URL =
  "https://bencrane--data-engine-x-txdot-letting-ingest-trigger-ing-5a912b.modal.run";

export const txdotLettingMonthly = schedules.task({
  id: "txdot-letting.monthly",
  cron: "0 8 1 * *", // 1st of month, 08:00 UTC
  maxDuration: 600,
  run: async (_payload, { ctx }) => {
    if (!(await passesGate("txdot-letting.monthly"))) return SKIPPED_DISABLED;
    const snapshotDate = new Date().toISOString().slice(0, 10); // YYYY-MM-DD UTC

    // Modal fastapi_endpoint with method="POST" maps function args to query
    // params by default (no Pydantic body schema declared). Pass snapshot_date
    // via query string.
    const url = `${MODAL_TRIGGER_URL}?snapshot_date=${encodeURIComponent(snapshotDate)}`;

    logger.info("txdot-letting.monthly: spawning Modal ingest", {
      url,
      snapshot_date: snapshotDate,
      trigger_run_id: ctx.run.id,
    });

    const resp = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
    });

    if (!resp.ok) {
      const text = await resp.text();
      throw new Error(`Modal trigger_ingest_via_http ${resp.status}: ${text}`);
    }

    const data = (await resp.json()) as {
      call_id: string;
      snapshot_date: string;
    };
    logger.info("txdot-letting.monthly: Modal call spawned", {
      call_id: data.call_id,
      snapshot_date: data.snapshot_date,
      trigger_run_id: ctx.run.id,
    });
    return data;
  },
});
