-- DMaaS (Direct Mail as a Service) — scaffolds + designs + authoring sessions.
--
-- Architecture: design splits into two layers.
--   * Scaffolds — durable layout structures with constraint specs. Authored
--     once (with future LLM assist via the scaffold-authoring agent), serve
--     thousands of mailers. Constraints are stored as JSONB DSL, not code,
--     so they're debuggable assets.
--   * Designs — per-mailer content filling a scaffold's slots. Generated by
--     the content agent at runtime. The agent doesn't reason about layout —
--     only words, color assignments, and which scaffold to pick.
--
-- Scaffolds reference direct_mail_specs (mailer_category, variant) and the
-- constraint DSL references zones from those specs. Solver translates the
-- DSL → kiwisolver (server-side) or @lume/kiwi (browser-side) constraints.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Scaffolds: layout templates. One scaffold + one (spec, content) pair →
-- one fully resolved layout.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dmaas_scaffolds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    -- Print format gate. Only `postcard` is active in v1; column is here so
    -- adding letters/self-mailers later doesn't need a schema change.
    format TEXT NOT NULL
        CHECK (format IN ('postcard', 'letter', 'self_mailer', 'snap_pack', 'booklet')),
    -- [{category: "postcard", variant: "6x9"}, ...] — specs this scaffold
    -- can render against. Authoring step verifies the solver passes for
    -- each entry before allowing the scaffold to save.
    compatible_specs JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- JSON Schema for the content_config a design must supply. Validated
    -- on design create / update via the jsonschema library.
    prop_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Constraint DSL — the structured layout spec. See app/dmaas/dsl.py for
    -- the full set of supported constraint types.
    constraint_specification JSONB NOT NULL,
    preview_image_url TEXT,
    vertical_tags TEXT[] NOT NULL DEFAULT '{}',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    -- Scaffolds are versioned via INSERT-new-row (slug stays, version_number
    -- bumps; the latest active row by version_number is "the" scaffold).
    version_number INT NOT NULL DEFAULT 1,
    created_by_user_id UUID REFERENCES business.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dmaas_scaffolds_format_active
    ON dmaas_scaffolds (format) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_dmaas_scaffolds_vertical_tags
    ON dmaas_scaffolds USING GIN (vertical_tags);
CREATE INDEX IF NOT EXISTS idx_dmaas_scaffolds_compatible_specs
    ON dmaas_scaffolds USING GIN (compatible_specs);

-- ---------------------------------------------------------------------------
-- Designs: a scaffold + a spec + a content_config. Solver runs on save and
-- caches resolved positions so the renderer doesn't re-solve on every read.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dmaas_designs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scaffold_id UUID NOT NULL REFERENCES dmaas_scaffolds(id) ON DELETE RESTRICT,
    -- Spec the design is rendered against (composite FK to direct_mail_specs).
    spec_category TEXT NOT NULL,
    spec_variant TEXT NOT NULL,
    -- Per-mailer content filling the scaffold's prop_schema slots.
    content_config JSONB NOT NULL,
    -- Solver output: {element_name: {x, y, w, h}} in pixels @ spec DPI. Cached
    -- on save so the renderer + frontend don't re-solve on read.
    resolved_positions JSONB NOT NULL,
    brand_id UUID REFERENCES business.brands(id) ON DELETE SET NULL,
    -- audience_templates table doesn't exist yet — column is here as a
    -- future link target; no FK enforcement until that table lands.
    audience_template_id UUID,
    created_by_user_id UUID REFERENCES business.users(id) ON DELETE SET NULL,
    version_number INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (spec_category, spec_variant)
        REFERENCES direct_mail_specs (mailer_category, variant) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_dmaas_designs_scaffold ON dmaas_designs (scaffold_id);
CREATE INDEX IF NOT EXISTS idx_dmaas_designs_brand ON dmaas_designs (brand_id);
CREATE INDEX IF NOT EXISTS idx_dmaas_designs_audience
    ON dmaas_designs (audience_template_id) WHERE audience_template_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_dmaas_designs_spec ON dmaas_designs (spec_category, spec_variant);

-- ---------------------------------------------------------------------------
-- Audit trail of LLM-assisted scaffold creation. scaffold_id is NULL until
-- the operator accepts a session and a scaffold row is created from it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dmaas_scaffold_authoring_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scaffold_id UUID REFERENCES dmaas_scaffolds(id) ON DELETE SET NULL,
    prompt TEXT NOT NULL,
    proposed_constraint_specification JSONB NOT NULL,
    accepted BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    created_by_user_id UUID REFERENCES business.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dmaas_authoring_scaffold
    ON dmaas_scaffold_authoring_sessions (scaffold_id) WHERE scaffold_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_dmaas_authoring_user
    ON dmaas_scaffold_authoring_sessions (created_by_user_id);
