#!/usr/bin/env bash
# Rollback harness for directive: 2026-05-03-source-sbir-awards-ingest
# Generated by audit subagent.
#
# Reverses the migration in REVERSE order of forward apply (s3 → s2 → s1).
#
# s3 (Railway deploy):
#   Railway CLI 4.33.0 has NO `redeploy --deployment-id` flag (validator confirmed).
#   The actionable rollback path is `git revert <merge-SHA>` on bencrane/hq-all main
#   → push → Railway auto-redeploys the reverted SHA. This is exactly what stage 3.5
#   deploy-verifier does automatically when post-deploy verification fails (open
#   hotfix-revert PR + auto-merge). When this script is invoked manually outside
#   the orchestrator, it does the same thing.
#
# s2 (code):
#   Subsumed by s3's git revert — there is no separate filesystem rollback. Pre-merge
#   rollback is implicit (don't merge). Marked `true` so the runner reports OK without
#   doing duplicate work.
#
# s1 (migration):
#   Apply paired down-migration (DROP TABLE IF EXISTS ... CASCADE on the source table
#   AND the audit table). Pure additive surface — no FKs out, no downstream consumers
#   — so the drop is safe. NOTE: this is a NEW pattern for source_* tables in this
#   repo (no neighbor source_* migration has a paired _down.sql); accepted by the
#   audit because the additive-only safety case is unusually clean. CLAUDE.md does
#   NOT prohibit down-migrations.
#
# MERGE_SHA env var is required for s3. If unset, s3 errors loudly and exits 2.
# SURFACE_FILTER + REPO_FILTER work as in the other rollback scripts in this dir.
#
# Usage:
#   MERGE_SHA=abc1234 ./2026-05-03-source-sbir-awards-ingest-rollback.sh
#   ./2026-05-03-source-sbir-awards-ingest-rollback.sh --surface s1
#   ./2026-05-03-source-sbir-awards-ingest-rollback.sh --repo data-engine-x

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="/Users/benjamincrane/hq-all"
APP_DIR="$HQ_ALL/apps/data-engine-x"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

echo "==> Rolling back source_sbir_awards surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

# REVERSE order: s3 → s2 → s1.

# s3 — deploy: open hotfix-revert PR on bencrane/hq-all and auto-merge it. Railway
# auto-redeploys the reverted SHA. Requires $MERGE_SHA to be set in the environment.
rollback_surface "s3" "data-engine-x" 'if [[ -z "${MERGE_SHA:-}" ]]; then echo "FAIL: MERGE_SHA env var must be set for s3 rollback" >&2; exit 2; fi && \
  cd "$HQ_ALL" && \
  git fetch origin main && \
  BR="hotfix/revert-2026-05-03-source-sbir-awards-ingest-$(date -u +%Y%m%d-%H%M%S)" && \
  git checkout -b "$BR" origin/main && \
  git revert --no-edit "$MERGE_SHA" && \
  git push -u origin "$BR" && \
  gh -R bencrane/hq-all pr create --title "Revert: 2026-05-03-source-sbir-awards-ingest (deploy verification failed)" --body "Auto-generated revert. Deploy of $MERGE_SHA failed verification. Directive: /Users/benjamincrane/Desktop/hq/directives/2026-05-03-source-sbir-awards-ingest.md" --base main && \
  gh -R bencrane/hq-all pr merge --merge --auto --delete-branch'

# s2 — code: subsumed by s3's git revert. No separate filesystem action.
rollback_surface "s2" "data-engine-x" 'echo "s2 rollback subsumed by s3 git revert (no separate filesystem action)" && true'

# s1 — migration: apply paired down-migration via Doppler/psql against $DEX_DB_URL_DIRECT.
rollback_surface "s1" "data-engine-x" 'cd "$APP_DIR" && doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -v ON_ERROR_STOP=1 -f supabase/migrations/20260503140000_sbir_source_tables_down.sql'"'"''

echo "==> Rollback complete."
