#!/usr/bin/env bash
# Verification harness for directive: 2026-05-03-overture-places-ingest
# Generated by audit subagent.
#
# Surfaces (5, single repo bencrane/hq-all → apps/data-engine-x):
#   s1  migration  apps/data-engine-x/supabase/migrations/{ts}_create_source_overture_places.sql
#                  → entities.source_overture_places (overture_id PK + 1:1 mirror + provenance + raw_source_row)
#                  → ops.overture_places_ingest_runs (run-grain audit table)
#   s2  code       apps/data-engine-x/scripts/run_overture_places_ingest.py
#                  → static checks (file tracked + parses + has expected shape)
#   s3  code       apps/data-engine-x/modal/overture_places_ingest_app.py
#                  → static checks (file tracked + parses + has app-name + cron + secret)
#   s4  config     Modal named secret `overture-places-db`
#                  → modal secret list shows the named secret
#   s5  deploy     Modal app `data-engine-x-overture-places-ingest`
#                  → modal app list shows app deployed (post-`modal deploy`)
#
# Doppler idiom (per apps/data-engine-x/CLAUDE.md §"Doppler Shell Gotcha"):
#   doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -c "..."'
# The bash -c subshell defers $VAR expansion until after Doppler injects.
# Bare `doppler run -- psql "$DEX_DB_URL_DIRECT" -c ...` expands in the parent
# shell BEFORE Doppler — connecting to local Postgres or empty.
# Doppler project/config is pinned per-directory via apps/data-engine-x/doppler.yaml
# (project=hq-all, config=prd; the CLAUDE.md text saying project=data-engine-x is stale).
#
# Usage:
#   ./2026-05-03-overture-places-ingest.sh
#   ./2026-05-03-overture-places-ingest.sh --surface s1
#   ./2026-05-03-overture-places-ingest.sh --repo data-engine-x
#
# Exits 0 only if every requested surface passes.

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="/Users/benjamincrane/hq-all"
APP_DIR="$HQ_ALL/apps/data-engine-x"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

# Sidecar SQL file (NPPES precedent: 2026-05-02-nppes-targeting-mvs-verify.sql).
# Avoids the 3-deep quoting hell of bash -c '...' wrapping psql -c "..." with
# embedded SQL string literals — \047 and \" both fail to render through
# eval → bash -c → psql. Heredoc-rendered file + psql -f is the clean path.
S1_SQL_FILE="$SCRIPT_DIR/2026-05-03-overture-places-ingest-s1-verify.sql"
cat > "$S1_SQL_FILE" <<'EOF'
SELECT (
  (SELECT COUNT(*) FROM information_schema.tables
     WHERE table_schema = 'entities'
       AND table_name   = 'source_overture_places') = 1
  AND
  (SELECT COUNT(*) FROM information_schema.tables
     WHERE table_schema = 'ops'
       AND table_name   = 'overture_places_ingest_runs') = 1
)::int;
EOF

# Confirm hq-all has bencrane/hq-all as origin remote (not a fork or stale clone).
REMOTE=$(git -C "$HQ_ALL" remote get-url origin 2>&1 || echo "MISSING")
if [[ "$REMOTE" != *"bencrane/hq-all"* ]]; then
  echo "FAIL: $HQ_ALL origin is '$REMOTE' — expected bencrane/hq-all" >&2
  exit 1
fi

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then
    echo "-- $id ($repo): SKIPPED (surface filter)"
    return 0
  fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (repo filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

echo "==> Verifying overture-places-ingest surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

# Surface s1 — migration: BOTH tables must exist with expected names.
# Uses sidecar SQL file (NPPES precedent) so we don't have to thread quotes
# through outer-eval → bash -c → psql -c (3 layers, \047 and \" both fail).
# The SQL file returns 1 iff both tables exist in the expected schemas.
run_surface "s1" "data-engine-x" "cd \"\$APP_DIR\" && result=\$(doppler run -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -tAX -v ON_ERROR_STOP=1 -f $S1_SQL_FILE') && [[ \"\$result\" == \"1\" ]]"

# Surface s2 — code: ingest script tracked in git, parses, references the expected
# table names, env var, ON CONFLICT, and raw_source_row column.
run_surface "s2" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/scripts/run_overture_places_ingest.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/scripts/run_overture_places_ingest.py\").read())" && \
  grep -q "entities.source_overture_places" apps/data-engine-x/scripts/run_overture_places_ingest.py && \
  grep -q "ops.overture_places_ingest_runs" apps/data-engine-x/scripts/run_overture_places_ingest.py && \
  grep -q "DEX_DB_URL_POOLED" apps/data-engine-x/scripts/run_overture_places_ingest.py && \
  grep -q "ON CONFLICT" apps/data-engine-x/scripts/run_overture_places_ingest.py && \
  grep -q "raw_source_row" apps/data-engine-x/scripts/run_overture_places_ingest.py'

# Surface s3 — code: Modal wrapper tracked in git, parses, declares the expected
# app name, cron schedule, and named secret.
run_surface "s3" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/modal/overture_places_ingest_app.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/modal/overture_places_ingest_app.py\").read())" && \
  grep -q "data-engine-x-overture-places-ingest" apps/data-engine-x/modal/overture_places_ingest_app.py && \
  grep -q "modal.Cron(\"0 0 5 \* \*\")" apps/data-engine-x/modal/overture_places_ingest_app.py && \
  grep -q "from_name(\"overture-places-db\")" apps/data-engine-x/modal/overture_places_ingest_app.py'

# Surface s4 — config: Modal secret `overture-places-db` exists.
# Reviewer-confirmed: `modal secret list --json` (CLI 1.4.x) returns
# TitleCase {"Name", "Created at", ...} — same pattern as `app list --json`.
# Audit's original `select(.name == ...)` matches NOTHING because the key is
# `Name`, not `name`. Use `(.Name // .name)` fallback for resilience across
# CLI versions.
run_surface "s4" "data-engine-x" 'modal secret list --json | jq -e '"'"'.[] | select((.Name // .name) == "overture-places-db")'"'"' >/dev/null'

# Surface s5 — deploy: Modal app `data-engine-x-overture-places-ingest` is deployed.
# Per validator notes, `modal app list --json` exposes the app name under either
# "Description" or "name" and the deploy state under either "State" or "state"
# (Modal CLI 1.4.x uses TitleCase keys; older versions used lowercase). Tolerate
# both shapes via `// fallbacks` so this verify works across CLI versions.
run_surface "s5" "data-engine-x" 'modal app list --json | jq -e '"'"'.[] | select(((.["Description"] // .name) == "data-engine-x-overture-places-ingest") and (((.["State"] // .state) | ascii_downcase) == "deployed"))'"'"' >/dev/null'

echo "==> All requested surfaces verified."
