#!/usr/bin/env bash
# Verification harness for directive: 2026-05-02-nppes-targeting-mvs
# Generated by audit subagent.
#
# Surface s1: comprehensive check of all 4 artifacts created by
#   supabase/migrations/20260503150000_mv_nppes_provider_targeting.sql:
#     - entities.mv_nppes_provider_targeting       (MV exists, populated, > 0 rows)
#     - entities.mv_nppes_signal_delta_new_enumerations (MV exists, populated, >= 0 rows)
#     - ops.refresh_mv_nppes_provider_targeting    (function exists)
#     - ops.refresh_mv_nppes_signal_delta_new_enumerations (function exists)
#     - cron.job rows for both refresh jobnames    (count = 2)
#
# Returns "1" iff every assertion holds. Exits non-zero otherwise.
# Usage: ./2026-05-02-nppes-targeting-mvs.sh [--repo data-engine-x]

set -euo pipefail

REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

REPO_DIR="/Users/benjamincrane/Desktop/hq-all/apps/data-engine-x"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SQL_FILE="$SCRIPT_DIR/2026-05-02-nppes-targeting-mvs-verify.sql"

cat > "$SQL_FILE" <<'EOF'
SELECT (
  (SELECT COUNT(*) FROM pg_matviews
     WHERE schemaname = 'entities'
       AND matviewname = 'mv_nppes_provider_targeting'
       AND ispopulated) = 1
  AND (SELECT COUNT(*) FROM pg_matviews
         WHERE schemaname = 'entities'
           AND matviewname = 'mv_nppes_signal_delta_new_enumerations'
           AND ispopulated) = 1
  AND (SELECT COUNT(*) FROM entities.mv_nppes_provider_targeting) > 0
  AND (SELECT COUNT(*) FROM pg_proc p
         JOIN pg_namespace n ON p.pronamespace = n.oid
        WHERE n.nspname = 'ops'
          AND p.proname IN (
            'refresh_mv_nppes_provider_targeting',
            'refresh_mv_nppes_signal_delta_new_enumerations'
          )) = 2
  AND (SELECT COUNT(*) FROM cron.job
         WHERE jobname IN (
           'refresh_mv_nppes_provider_targeting',
           'refresh_mv_nppes_signal_delta_new_enumerations'
         )) = 2
)::int;
EOF

echo "==> Verifying NPPES targeting MV surfaces (filter: ${REPO_FILTER:-all})"

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if ( cd "$REPO_DIR" && eval "$cmd" ); then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

# Surface s1: comprehensive check.
# `result=$(...)` then `[[ "$result" == "1" ]]` — psql returns "1" only when every
# subquery in the SQL above evaluates true. Any other value (incl. "0", "f", or
# error output) trips the assertion.
run_surface "s1" "data-engine-x" "result=\$(doppler run -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -tAX -v ON_ERROR_STOP=1 -f $SQL_FILE') && [[ \"\$result\" == \"1\" ]]"

# Optional sanity prints (informational only — do not affect exit code).
echo "==> Sanity counts:"
( cd "$REPO_DIR" && doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT '\''mv_nppes_provider_targeting rows='\'' || COUNT(*) FROM entities.mv_nppes_provider_targeting;"' || true )
( cd "$REPO_DIR" && doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT '\''mv_nppes_signal_delta_new_enumerations rows='\'' || COUNT(*) FROM entities.mv_nppes_signal_delta_new_enumerations;"' || true )
( cd "$REPO_DIR" && doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT '\''cron jobs registered=='\'' || COALESCE(string_agg(jobname, '\'','\''), '\''<none>'\'') FROM cron.job WHERE jobname IN ('\''refresh_mv_nppes_provider_targeting'\'','\''refresh_mv_nppes_signal_delta_new_enumerations'\'');"' || true )

echo "All requested surfaces verified."
