#!/usr/bin/env bash
# Verification harness for directive: 2026-05-03-faa-airmen-ingest
# Generated by audit subagent.
#
# Surfaces (5, single repo bencrane/hq-all → apps/data-engine-x):
#   s1  migration  apps/data-engine-x/supabase/migrations/{ts}_create_source_faa_airmen.sql
#                  → entities.source_faa_airmen_pilot_basic     (PK unique_id)
#                  → entities.source_faa_airmen_pilot_cert      (PK unique_id, certificate_type, certificate_level)
#                  → entities.source_faa_airmen_nonpilot_basic  (PK unique_id)
#                  → entities.source_faa_airmen_nonpilot_cert   (PK unique_id, certificate_type, certificate_level)
#                  → ops.faa_airmen_ingest_runs (run-grain audit table)
#                  Each table: 1:1 mirror of CSV columns + raw_source_row jsonb NOT NULL
#                  + full 9-col canonical provenance set.
#   s2  code       apps/data-engine-x/scripts/run_faa_airmen_ingest.py
#                  → static checks (file tracked + parses + has expected shape)
#   s3  code       apps/data-engine-x/modal/faa_airmen_ingest_app.py
#                  → static checks (file tracked + parses + app-name/cron/secret)
#   s4  config     Modal named secret `faa-airmen-db`
#                  → modal secret list shows the named secret
#   s5  deploy     Modal app `data-engine-x-faa-airmen-ingest`
#                  → modal app list shows app deployed (post-`modal deploy`)
#                  → ops.faa_airmen_ingest_runs latest row succeeded
#                  → 4× dex_min_row_floor_check on the 4 source tables
#                  → dex_idempotency_check second-run preserves COUNT
#
# Doppler idiom (per apps/data-engine-x/CLAUDE.md §"Doppler shell gotcha"):
#   doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -c "..."'
# Doppler project/config pinned per-directory via apps/data-engine-x/doppler.yaml
# (project=hq-all, config=prd; the CLAUDE.md text saying project=data-engine-x
# is stale per validator notes lines 138-142).
#
# Source ingest invariant + helper library: helper functions
# (dex_provenance_check, dex_min_row_floor_check, dex_idempotency_check) come
# from apps/data-engine-x/scripts/_lib/dex.sh — sourced via the vault thin shim.
#
# Usage:
#   ./2026-05-03-faa-airmen-ingest.sh
#   ./2026-05-03-faa-airmen-ingest.sh --surface s1
#   ./2026-05-03-faa-airmen-ingest.sh --repo data-engine-x
#
# Exits 0 only if every requested surface passes.

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="${HQ_ALL:-/Users/benjamincrane/hq-all}"
APP_DIR="$HQ_ALL/apps/data-engine-x"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source the shim once at top — exposes dex_psql_query, dex_psql_ddl,
# dex_provenance_check, dex_min_row_floor_check, dex_idempotency_check.
# shellcheck source=/dev/null
source "$HOME/Desktop/hq-all/apps/data-engine-x/scripts/migration-checks/_lib-shim.sh"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

# Sidecar SQL file (Overture precedent: 2026-05-03-overture-places-ingest-s1-verify.sql).
# Returns single integer 1 iff all 4 source tables + ops table exist.
S1_SQL_FILE="$SCRIPT_DIR/2026-05-03-faa-airmen-ingest-s1-verify.sql"
if [[ ! -f "$S1_SQL_FILE" ]]; then
  echo "FAIL: sidecar SQL missing: $S1_SQL_FILE" >&2
  exit 1
fi

# Confirm hq-all has bencrane/hq-all as origin remote (not a fork or stale clone).
REMOTE=$(git -C "$HQ_ALL" remote get-url origin 2>&1 || echo "MISSING")
if [[ "$REMOTE" != *"bencrane/hq-all"* ]]; then
  echo "FAIL: $HQ_ALL origin is '$REMOTE' — expected bencrane/hq-all" >&2
  exit 1
fi

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then
    echo "-- $id ($repo): SKIPPED (surface filter)"
    return 0
  fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (repo filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

echo "==> Verifying faa-airmen-ingest surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

# s1 — migration: all 4 source tables + ops runs table exist (sidecar SQL),
# AND each source table has the canonical 9-column provenance set.
run_surface "s1" "data-engine-x" 'dex_psql_query "$(cat '"$S1_SQL_FILE"')" | grep -q "^1$" && \
  dex_provenance_check entities.source_faa_airmen_pilot_basic && \
  dex_provenance_check entities.source_faa_airmen_pilot_cert && \
  dex_provenance_check entities.source_faa_airmen_nonpilot_basic && \
  dex_provenance_check entities.source_faa_airmen_nonpilot_cert'

# s2 — code: ingest script tracked, parses, references all 4 tables + ops table
# + DEX_DB_URL_POOLED + ON CONFLICT + raw_source_row + registry.faa.gov URL host.
run_surface "s2" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/scripts/run_faa_airmen_ingest.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/scripts/run_faa_airmen_ingest.py\").read())" && \
  grep -q "entities.source_faa_airmen_pilot_basic" apps/data-engine-x/scripts/run_faa_airmen_ingest.py && \
  grep -q "entities.source_faa_airmen_pilot_cert" apps/data-engine-x/scripts/run_faa_airmen_ingest.py && \
  grep -q "entities.source_faa_airmen_nonpilot_basic" apps/data-engine-x/scripts/run_faa_airmen_ingest.py && \
  grep -q "entities.source_faa_airmen_nonpilot_cert" apps/data-engine-x/scripts/run_faa_airmen_ingest.py && \
  grep -q "ops.faa_airmen_ingest_runs" apps/data-engine-x/scripts/run_faa_airmen_ingest.py && \
  grep -q "DEX_DB_URL_POOLED" apps/data-engine-x/scripts/run_faa_airmen_ingest.py && \
  grep -q "ON CONFLICT" apps/data-engine-x/scripts/run_faa_airmen_ingest.py && \
  grep -q "raw_source_row" apps/data-engine-x/scripts/run_faa_airmen_ingest.py && \
  grep -q "registry.faa.gov" apps/data-engine-x/scripts/run_faa_airmen_ingest.py'

# s3 — code: Modal wrapper tracked, parses, declares the expected app name,
# cron schedule, and named secret.
run_surface "s3" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/modal/faa_airmen_ingest_app.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/modal/faa_airmen_ingest_app.py\").read())" && \
  grep -q "data-engine-x-faa-airmen-ingest" apps/data-engine-x/modal/faa_airmen_ingest_app.py && \
  grep -q "modal.Cron(\"0 0 5 \* \*\")" apps/data-engine-x/modal/faa_airmen_ingest_app.py && \
  grep -q "from_name(\"faa-airmen-db\")" apps/data-engine-x/modal/faa_airmen_ingest_app.py'

# s4 — config: Modal secret `faa-airmen-db` exists.
# Tolerant of CLI key shape (Modal CLI 1.4.x TitleCase Name vs older lowercase
# name) per validator notes — same fallback as Overture precedent.
run_surface "s4" "data-engine-x" 'modal secret list --json | jq -e '"'"'.[] | select((.Name // .name) == "faa-airmen-db")'"'"' >/dev/null'

# s5 — deploy: Modal app `data-engine-x-faa-airmen-ingest` is deployed AND
# the latest ops run row is 'succeeded' AND the 4 source tables hit their
# published-count floors AND running the ingest a second time is idempotent
# (dex_idempotency_check on PILOT_CERT — largest table per `## Volume floors`
# AND the table where composite-PK collision risk lives, so it's the strongest
# single-table idempotency probe).
run_surface "s5" "data-engine-x" 'modal app list --json | jq -e '"'"'.[] | select(((.["Description"] // .name) == "data-engine-x-faa-airmen-ingest") and (((.["State"] // .state) | ascii_downcase) == "deployed"))'"'"' >/dev/null && \
  [[ "$(dex_psql_query "SELECT status FROM ops.faa_airmen_ingest_runs ORDER BY started_at DESC LIMIT 1")" == "succeeded" ]] && \
  dex_min_row_floor_check entities.source_faa_airmen_pilot_basic 1000000 && \
  dex_min_row_floor_check entities.source_faa_airmen_pilot_cert 1500000 && \
  dex_min_row_floor_check entities.source_faa_airmen_nonpilot_basic 600000 && \
  dex_min_row_floor_check entities.source_faa_airmen_nonpilot_cert 700000 && \
  dex_idempotency_check "doppler run --project hq-all --config prd -- modal run apps/data-engine-x/modal/faa_airmen_ingest_app.py::run_ingest" entities.source_faa_airmen_pilot_cert'

echo "==> All requested surfaces verified."
