#!/usr/bin/env bash
# Rollback harness for directive: 2026-05-03-state-contractor-license-rosters
# SCAFFOLD GENERATED BY VALIDATOR. Audit subagent fills per-surface rollbacks
# (and may emit per-state rollback scripts if scope-decomposer SPLITs).
#
# Rollback ordering: REVERSE of apply order, per state.
#   For state CA: s3 (deploy/schedule) → s2 (code) → s1 (migration)
#   For state TX: s6 → s5 → s4
#   ... etc. across CA / TX / FL / AZ / NC
# When run without --state filter, rolls back state-by-state in reverse alphabetical
# order: NC → AZ → FL → TX → CA (so the LAST-applied state is rolled back first).
# When run with --state, only that state's surfaces are rolled back.
# When run with --surface, only that single surface is rolled back.
#
# Per-surface rollback shape (audit fills the actual commands):
#
#   Migration surface (s1, s4, s7, s10, s13):
#     Paired down-migration named {ts}_state_contractor_<abbr>_source_tables_down.sql
#     Issuing DROP TABLE IF EXISTS entities.source_state_contractor_<abbr> CASCADE.
#     PLUS DROP TABLE IF EXISTS ops.state_contractor_<abbr>_ingest_runs (if the
#     audit decides to add a sibling audit table per the source_* precedent).
#     Apply via: doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -f <down.sql>'
#     (CASCADE chosen because no MV references the source tables — verified by
#     the directive's `## Out of scope` "no cross-state union MV". Audit must
#     re-confirm at audit time that no orphan FK / no MV depends on the table.)
#
#   Code surface (s2, s5, s8, s11, s14):
#     `git revert <merge-SHA>` on bencrane/hq-all main. Cannot revert the script
#     file alone if the migration + script merged in one PR — revert the whole
#     PR. The down-migration above takes care of the table; the revert removes
#     the script. Railway main-watch auto-redeploys the revert.
#
#   Deploy + schedule surface (s3, s6, s9, s12, s15):
#     The Railway service `data-engine-x` redeploys on every push to main; the
#     revert in the previous step IS the deploy rollback. No separate Railway
#     action needed — `railway redeploy` only redeploys LATEST and is not the
#     right tool for "go back to a prior SHA" (CLI 4.33.0).
#     Schedule rollback depends on which scheduling surface the audit picked:
#       (a) shell-cron — remove `cron_state_contractor_<abbr>_refresh.sh` (or
#           leave it and just remove its crontab entry on the host; the host is
#           unspecified in this repo, audit must clarify).
#       (b) Trigger.dev task — `npx trigger.dev@latest deploy --env prod` after
#           removing/disabling the task. Not in current repo precedent.
#       (c) Railway cron service — remove the service or null its cronSchedule.
#           Not in current repo precedent.
#
# Usage:
#   ./2026-05-03-state-contractor-license-rosters-rollback.sh                  # all 15 surfaces, reverse order
#   ./2026-05-03-state-contractor-license-rosters-rollback.sh --state ca       # only CA's 3 surfaces
#   ./2026-05-03-state-contractor-license-rosters-rollback.sh --surface s1     # only the CA migration
#   MERGE_SHA=abc1234 ./2026-05-03-state-contractor-license-rosters-rollback.sh

set -euo pipefail

STATE_FILTER=""
SURFACE_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --state) STATE_FILTER="$2"; shift 2 ;;
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="/Users/benjamincrane/hq-all"
APP_DIR="$HQ_ALL/apps/data-engine-x"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

REMOTE=$(git -C "$HQ_ALL" remote get-url origin 2>&1 || echo "MISSING")
if [[ "$REMOTE" != *"bencrane/hq-all"* ]]; then
  echo "FAIL: $HQ_ALL origin is '$REMOTE' — expected bencrane/hq-all" >&2
  exit 1
fi

rollback_surface() {
  local id="$1" state="$2" cmd="$3"
  if [[ -n "$STATE_FILTER" && "$STATE_FILTER" != "$state" ]]; then
    echo "-- $id ($state): SKIPPED (state filter)"
    return 0
  fi
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then
    echo "-- $id ($state): SKIPPED (surface filter)"
    return 0
  fi
  echo "-- $id ($state): ROLLING BACK"
  if eval "$cmd"; then
    echo "-- $id ($state): ROLLED BACK"
  else
    echo "-- $id ($state): ROLLBACK FAILED" >&2
    return 1
  fi
}

echo "==> Rolling back state-contractor source surfaces (filter: state=${STATE_FILTER:-all} surface=${SURFACE_FILTER:-all}, MERGE_SHA: ${MERGE_SHA:-<unset>})"

# AUDIT SUBAGENT: fill rollback commands once down-migration filenames are
# locked. The placeholders below are intentionally non-executable (`false # AUDIT:`)
# so an unfilled rollback FAILS LOUDLY rather than silently passing.
#
# Reverse order (LAST applied → FIRST applied):
#   NC: s15 → s14 → s13
#   AZ: s12 → s11 → s10
#   FL: s9  → s8  → s7
#   TX: s6  → s5  → s4
#   CA: s3  → s2  → s1

rollback_surface "s15" "nc" 'false # AUDIT: fill — NC deploy/schedule rollback (revert merge-SHA + unschedule per chosen scheduler)'
rollback_surface "s14" "nc" 'false # AUDIT: fill — NC code rollback (covered by git revert in s15 if same PR — confirm)'
rollback_surface "s13" "nc" 'false # AUDIT: fill — NC down-migration: DROP TABLE IF EXISTS entities.source_state_contractor_nc CASCADE'
rollback_surface "s12" "az" 'false # AUDIT: fill — AZ deploy/schedule rollback'
rollback_surface "s11" "az" 'false # AUDIT: fill — AZ code rollback'
rollback_surface "s10" "az" 'false # AUDIT: fill — AZ down-migration: DROP TABLE IF EXISTS entities.source_state_contractor_az CASCADE'
rollback_surface "s9"  "fl" 'false # AUDIT: fill — FL deploy/schedule rollback'
rollback_surface "s8"  "fl" 'false # AUDIT: fill — FL code rollback'
rollback_surface "s7"  "fl" 'false # AUDIT: fill — FL down-migration: DROP TABLE IF EXISTS entities.source_state_contractor_fl CASCADE'
rollback_surface "s6"  "tx" 'false # AUDIT: fill — TX deploy/schedule rollback'
rollback_surface "s5"  "tx" 'false # AUDIT: fill — TX code rollback'
rollback_surface "s4"  "tx" 'false # AUDIT: fill — TX down-migration: DROP TABLE IF EXISTS entities.source_state_contractor_tx CASCADE'
rollback_surface "s3"  "ca" 'false # AUDIT: fill — CA deploy/schedule rollback'
rollback_surface "s2"  "ca" 'false # AUDIT: fill — CA code rollback'
rollback_surface "s1"  "ca" 'false # AUDIT: fill — CA down-migration: DROP TABLE IF EXISTS entities.source_state_contractor_ca CASCADE'

echo "==> All requested rollbacks completed."
