#!/usr/bin/env bash
# Rollback harness for directive: 2026-05-03-overture-places-ingest
# Generated by audit subagent.
#
# Reverses the migration in REVERSE order (s5 → s4 → s3 → s2 → s1).
#
# s5 (Modal app deploy):
#   `modal app rollback data-engine-x-overture-places-ingest` — first-class CLI
#   command (per `modal app rollback --help`) that redeploys the previous
#   version of the App from Modal's side. Falls back to `modal app stop` if
#   no prior version exists (first-ever deploy).
#
# s4 (Modal secret):
#   If newly created (executor recorded SECRET_PRE_EXISTED=0 in the directive's
#   ## Execution log): `modal secret delete overture-places-db`.
#   If pre-existing (SECRET_PRE_EXISTED=1): no-op (don't touch the operator's
#   secret). Default: skip with a warning if SECRET_PRE_EXISTED is unset, since
#   destructive default is unsafe.
#
# s3 + s2 (code):
#   Both files live on the merged commit. A single `git revert <merge-SHA>`
#   removes both. Pre-merge: don't merge (no rollback needed).
#
# s1 (migration):
#   Surface is purely additive (new tables, no existing data depends on them).
#   Repo convention is forward-only — no _down.sql precedent exists in
#   apps/data-engine-x/supabase/migrations/. Rollback is ad-hoc DROP CASCADE
#   via psql against $DEX_DB_URL_DIRECT (per directive deploy-target spec
#   confirmed by the validator).
#
# MERGE_SHA env var is required for s2/s3 git revert. SECRET_PRE_EXISTED env var
# (0 or 1) controls s4 behavior. Both are surfaced via standard rollback-script
# usage; callers are expected to set them based on the directive's
# ## Execution log.
#
# Usage:
#   MERGE_SHA=abc1234 SECRET_PRE_EXISTED=0 ./2026-05-03-overture-places-ingest-rollback.sh
#   ./2026-05-03-overture-places-ingest-rollback.sh --surface s1
#   ./2026-05-03-overture-places-ingest-rollback.sh --repo data-engine-x

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="/Users/benjamincrane/hq-all"
APP_DIR="$HQ_ALL/apps/data-engine-x"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

echo "==> Rolling back overture-places-ingest surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

# REVERSE order: s5 → s4 → s3 → s2 → s1.

# s5 — deploy: rollback the Modal app to its previous deployed version, or stop
# the app if this was the first-ever deploy. `modal app rollback` exits non-zero
# if there's no prior version; we fall back to `modal app stop` in that case.
rollback_surface "s5" "data-engine-x" 'cd "$APP_DIR" && \
  if doppler run --project hq-all --config prd -- modal app rollback data-engine-x-overture-places-ingest 2>&1 | tee /tmp/overture_rollback_s5.log; then \
    echo "s5: rolled back to previous deployed version"; \
  else \
    echo "s5: rollback failed (likely first-ever deploy) — falling back to stop"; \
    doppler run --project hq-all --config prd -- modal app stop data-engine-x-overture-places-ingest; \
  fi'

# s4 — config: delete the Modal secret iff it did not pre-exist.
# Caller must set SECRET_PRE_EXISTED to 0 (newly created) or 1 (pre-existing).
# Unset → skip (safer than wrongly deleting a pre-existing secret).
rollback_surface "s4" "data-engine-x" 'if [[ "${SECRET_PRE_EXISTED:-unset}" == "0" ]]; then \
    doppler run --project hq-all --config prd -- modal secret delete overture-places-db; \
  elif [[ "${SECRET_PRE_EXISTED:-unset}" == "1" ]]; then \
    echo "s4 rollback skipped: SECRET_PRE_EXISTED=1 (pre-existing — leaving operator-owned secret intact)"; \
    true; \
  else \
    echo "s4 rollback skipped: SECRET_PRE_EXISTED unset — refusing to delete potentially-pre-existing secret. Set SECRET_PRE_EXISTED=0 or 1 explicitly to enable rollback." >&2; \
    true; \
  fi'

# s3 — code: subsumed by s2's git revert below (single revert covers both files).
rollback_surface "s3" "data-engine-x" 'echo "s3 rollback subsumed by s2 git revert (same merge SHA covers both files)" && true'

# s2 — code: open hotfix-revert PR on bencrane/hq-all and auto-merge it.
# Requires $MERGE_SHA to be set. Repo convention: hq-all auto-merges via repo
# workflow once CI is green; we use --auto so the merge happens automatically.
rollback_surface "s2" "data-engine-x" 'if [[ -z "${MERGE_SHA:-}" ]]; then echo "FAIL: MERGE_SHA env var must be set for s2/s3 rollback" >&2; exit 2; fi && \
  cd "$HQ_ALL" && \
  git fetch origin main && \
  BR="hotfix/revert-2026-05-03-overture-places-ingest-$(date -u +%Y%m%d-%H%M%S)" && \
  git checkout -b "$BR" origin/main && \
  git revert --no-edit "$MERGE_SHA" && \
  git push -u origin "$BR" && \
  gh -R bencrane/hq-all pr create --title "Revert: 2026-05-03-overture-places-ingest" --body "Auto-generated revert. Directive: /Users/benjamincrane/Desktop/hq/directives/2026-05-03-overture-places-ingest.md" --base main && \
  gh -R bencrane/hq-all pr merge --merge --auto --delete-branch'

# s1 — migration: ad-hoc DROP CASCADE on both tables. Additive surface, safe drop.
rollback_surface "s1" "data-engine-x" 'cd "$APP_DIR" && doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -v ON_ERROR_STOP=1 -c "DROP TABLE IF EXISTS entities.source_overture_places CASCADE; DROP TABLE IF EXISTS ops.overture_places_ingest_runs CASCADE;"'"'"''

echo "==> Rollback complete."
