#!/usr/bin/env bash
# Verification harness for directive: 2026-05-03-source-sbir-awards-ingest
# Generated by audit subagent.
#
# Surfaces (3, all in bencrane/hq-all → apps/data-engine-x):
#   s1  migration  apps/data-engine-x/supabase/migrations/20260503140000_sbir_source_tables.sql
#                  → entities.source_sbir_awards (47 cols incl raw_source_row + provenance)
#                  → ops.sbir_ingest_runs (sibling audit table)
#                  → UNIQUE constraint source_sbir_awards_natural_key
#   s2  code       apps/data-engine-x/scripts/run_sbir_ingest.py
#                  → static checks (file exists, parses, has ON CONFLICT + raw_source_row)
#                  → smoke + idempotency stress test (run twice with --max-rows 100, assert N1==N2)
#                  → assert raw_source_row populated on every landed row
#   s3  deploy     Railway service `dex-api` (project data-engine-x)
#                  → latestDeployment.status == "SUCCESS"
#                  → latestDeployment.meta.commitHash matches ${MERGE_SHA} prefix
#
# Doppler idiom (from apps/data-engine-x/CLAUDE.md §"Doppler Shell Gotcha"):
#   doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -c "..."'
# The bash -c subshell defers $VAR expansion until after Doppler injects.
# Bare `doppler run -- psql "$DEX_DB_URL_DIRECT" -c ...` expands in the parent
# shell BEFORE Doppler — connecting to local Postgres or empty.
# Doppler project/config is pinned per-directory via apps/data-engine-x/doppler.yaml.
#
# Deploy verifier sets MERGE_SHA env var before invoking this script. s3 reads it
# from the environment; if unset, s3 still runs but only checks status==SUCCESS
# (the SHA-match assertion is skipped).
#
# Usage:
#   ./2026-05-03-source-sbir-awards-ingest.sh
#   ./2026-05-03-source-sbir-awards-ingest.sh --repo data-engine-x
#   MERGE_SHA=abc1234 ./2026-05-03-source-sbir-awards-ingest.sh

set -euo pipefail

REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="/Users/benjamincrane/hq-all"
APP_DIR="$HQ_ALL/apps/data-engine-x"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

# Confirm hq-all has bencrane/hq-all as origin remote (not a fork or stale clone).
REMOTE=$(git -C "$HQ_ALL" remote get-url origin 2>&1 || echo "MISSING")
if [[ "$REMOTE" != *"bencrane/hq-all"* ]]; then
  echo "FAIL: $HQ_ALL origin is '$REMOTE' — expected bencrane/hq-all" >&2
  exit 1
fi

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

echo "==> Verifying source_sbir_awards surfaces (filter: ${REPO_FILTER:-all}, MERGE_SHA: ${MERGE_SHA:-<unset>})"

# Surface s1 — migration: table+audit+constraint must all exist.
# psql returns 't' (true) only when all three sub-conditions hold.
run_surface "s1" "data-engine-x" 'cd "$APP_DIR" && result=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -v ON_ERROR_STOP=1 -c "SELECT (SELECT COUNT(*)::int FROM information_schema.columns WHERE table_schema='"'"'"'"'"'"'"'"'entities'"'"'"'"'"'"'"'"' AND table_name='"'"'"'"'"'"'"'"'source_sbir_awards'"'"'"'"'"'"'"'"') >= 45 AND (SELECT COUNT(*)::int FROM information_schema.tables WHERE table_schema='"'"'"'"'"'"'"'"'ops'"'"'"'"'"'"'"'"' AND table_name='"'"'"'"'"'"'"'"'sbir_ingest_runs'"'"'"'"'"'"'"'"') = 1 AND (SELECT COUNT(*)::int FROM information_schema.table_constraints WHERE table_schema='"'"'"'"'"'"'"'"'entities'"'"'"'"'"'"'"'"' AND table_name='"'"'"'"'"'"'"'"'source_sbir_awards'"'"'"'"'"'"'"'"' AND constraint_name='"'"'"'"'"'"'"'"'source_sbir_awards_natural_key'"'"'"'"'"'"'"'"' AND constraint_type='"'"'"'"'"'"'"'"'UNIQUE'"'"'"'"'"'"'"'"') = 1"'"'"' | tr -d "[:space:]") && [[ "$result" == "t" ]]'

# Surface s2 — code: script exists, parses, has key shape; smoke + idempotency stress test
# against prod DB. N1 must be >= 1 (rows landed); raw_source_row null-count must be 0;
# N1 must equal N2 (re-running same input doesn't grow the table).
run_surface "s2" "data-engine-x" 'cd "$APP_DIR" && \
  test -f scripts/run_sbir_ingest.py && \
  python3 -c "import ast; ast.parse(open(\"scripts/run_sbir_ingest.py\").read())" && \
  grep -q "ON CONFLICT" scripts/run_sbir_ingest.py && \
  grep -q "raw_source_row" scripts/run_sbir_ingest.py && \
  grep -q "source_sbir_awards" scripts/run_sbir_ingest.py && \
  grep -q "ops.sbir_ingest_runs" scripts/run_sbir_ingest.py && \
  PYTHONPATH=. doppler run -- python3 scripts/run_sbir_ingest.py --max-rows 100 >/tmp/sbir_run1.log 2>&1 && \
  N1=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT COUNT(*) FROM entities.source_sbir_awards;"'"'"' | tr -d "[:space:]") && \
  [[ "$N1" -ge 1 ]] && \
  NULL_RAW=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT COUNT(*) FROM entities.source_sbir_awards WHERE raw_source_row IS NULL;"'"'"' | tr -d "[:space:]") && \
  [[ "$NULL_RAW" == "0" ]] && \
  PYTHONPATH=. doppler run -- python3 scripts/run_sbir_ingest.py --max-rows 100 >/tmp/sbir_run2.log 2>&1 && \
  N2=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT COUNT(*) FROM entities.source_sbir_awards;"'"'"' | tr -d "[:space:]") && \
  [[ "$N1" == "$N2" ]] && \
  echo "s2 smoke+idempotency: N1=N2=$N1 raw_source_row populated"'

# Surface s3 — deploy: Railway dex-api latestDeployment must be SUCCESS at the merge SHA.
# Railway commit hashes are full 40-char; we match by 7-char prefix to be tolerant of how the
# orchestrator passes ${MERGE_SHA} (full SHA or short SHA both work).
# If MERGE_SHA is unset, fall back to status-only check (the deploy-verifier ALWAYS sets it
# before running this script per stage 3.5 contract).
run_surface "s3" "data-engine-x" 'cd "$APP_DIR" && \
  if [[ -n "${MERGE_SHA:-}" ]]; then \
    SHORT_SHA=$(printf "%s" "$MERGE_SHA" | cut -c1-7) && \
    railway status --json | jq -e --arg sha "$SHORT_SHA" '"'"'.environments.edges[].node.serviceInstances.edges[].node | select(.serviceName == "dex-api") | .latestDeployment | .status == "SUCCESS" and ((.meta.commitHash // "") | startswith($sha))'"'"'; \
  else \
    echo "WARN: MERGE_SHA unset — checking deploy status only, not SHA match" >&2 && \
    railway status --json | jq -e '"'"'.environments.edges[].node.serviceInstances.edges[].node | select(.serviceName == "dex-api") | .latestDeployment.status == "SUCCESS"'"'"'; \
  fi'

echo "==> All requested surfaces verified."
