#!/usr/bin/env bash
# Verification harness for directive: 2026-05-03-state-contractor-license-rosters
# SCAFFOLD GENERATED BY VALIDATOR. Audit subagent fills per-surface checks
# (and may emit per-state harness scripts if scope-decomposer SPLITs).
#
# Surfaces (15) — 3 per state x 5 states (CA / TX / FL / AZ / NC):
#   s1  migration  apps/data-engine-x/supabase/migrations/{ts}_state_contractor_ca_source_tables.sql
#   s2  code       apps/data-engine-x/scripts/run_state_contractor_ca_ingest.py
#                  (path corrected from directive draft —
#                  repo convention is scripts/run_<src>_ingest.py per
#                  run_gleif_ingest.py / run_hmda_ingest.py / run_dol_form5500_ingest.py;
#                  the directive's `ingest_state_contractor_ca.py` form is non-canonical)
#   s3  deploy     Railway service `data-engine-x` (project `hq-all`)
#                  + scheduling surface (per validator notes: there is NO Trigger.dev
#                  ingest precedent in this repo; ingestion is done by shell-cron pattern
#                  e.g. cron_dfpi_franchise_daily_refresh.sh — but Railway has NO cron
#                  schedules registered for any service in the hq-all project. The
#                  audit subagent must surface a concrete schedule registration target
#                  per state. Three viable patterns:
#                    a) shell script `apps/data-engine-x/scripts/cron_state_contractor_ca_refresh.sh`
#                       on a host crontab (matches DFPI/ACRIS/HPD precedents in scripts/)
#                       — but those scripts are NOT scheduled on Railway today; the
#                       host that runs them is unspecified in this repo.
#                    b) pg_cron job in a follow-up migration (precedent:
#                       20260503110000_mv_dfpi_signal_delta_filing_changes.sql —
#                       but pg_cron only triggers SQL, not external HTTP fetches,
#                       so this is unsuitable for a CSV-download ingest.)
#                    c) Add a Railway cron service with cronSchedule in the service
#                       manifest — NO precedent in hq-all today.
#                  The directive's "scheduled job" placeholder is genuinely unresolved
#                  at the repo level. Audit MUST resolve and document per state.
#   ... (s4..s15 follow the same shape per state — TX / FL / AZ / NC)
#
# Doppler idiom (from apps/data-engine-x/CLAUDE.md §"Doppler Shell Gotcha"):
#   doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -c "..."'
# The bash -c subshell defers $VAR expansion until after Doppler injects.
# Bare `doppler run -- psql "$DEX_DB_URL_DIRECT" -c ...` expands in the parent
# shell BEFORE Doppler — connecting to local Postgres or empty.
# Doppler project/config is pinned per-directory via apps/data-engine-x/doppler.yaml
# (project=data-engine-x, config=prd). The harness `cd`s into APP_DIR before
# invoking doppler so the pin is honored — no need to pass --project/--config.
#
# DEX_DB_URL_DIRECT is required for DDL / table-existence queries against the
# pooled-bouncer-incompatible session-mode features. DEX_DB_URL_POOLED works for
# row counts.
#
# Usage:
#   ./2026-05-03-state-contractor-license-rosters.sh
#   ./2026-05-03-state-contractor-license-rosters.sh --repo bencrane/hq-all
#   ./2026-05-03-state-contractor-license-rosters.sh --state ca
#   ./2026-05-03-state-contractor-license-rosters.sh --surface s1
#   MERGE_SHA=abc1234 ./2026-05-03-state-contractor-license-rosters.sh
#
# NOTE: if scope-decomposer SPLITs (expected — 15 surfaces > 5 threshold), this
# bundle script is superseded by 5 per-state harness scripts:
#   2026-05-03-state-contractor-ca.sh
#   2026-05-03-state-contractor-tx.sh
#   2026-05-03-state-contractor-fl.sh
#   2026-05-03-state-contractor-az.sh
#   2026-05-03-state-contractor-nc.sh
# Each per-state script keeps the same Doppler / Railway plumbing as below.

set -euo pipefail

REPO_FILTER=""
STATE_FILTER=""
SURFACE_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_FILTER="$2"; shift 2 ;;
    --state) STATE_FILTER="$2"; shift 2 ;;
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="/Users/benjamincrane/hq-all"
APP_DIR="$HQ_ALL/apps/data-engine-x"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

# Confirm hq-all has bencrane/hq-all as origin remote (not a fork or stale clone).
REMOTE=$(git -C "$HQ_ALL" remote get-url origin 2>&1 || echo "MISSING")
if [[ "$REMOTE" != *"bencrane/hq-all"* ]]; then
  echo "FAIL: $HQ_ALL origin is '$REMOTE' — expected bencrane/hq-all" >&2
  exit 1
fi

run_surface() {
  local id="$1" repo="$2" state="$3" cmd="$4"
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo / $state): SKIPPED (repo filter)"
    return 0
  fi
  if [[ -n "$STATE_FILTER" && "$STATE_FILTER" != "$state" ]]; then
    echo "-- $id ($repo / $state): SKIPPED (state filter)"
    return 0
  fi
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then
    echo "-- $id ($repo / $state): SKIPPED (surface filter)"
    return 0
  fi
  echo "-- $id ($repo / $state): RUNNING"
  if eval "$cmd"; then
    echo "-- $id ($repo / $state): PASS"
  else
    echo "-- $id ($repo / $state): FAIL" >&2
    return 1
  fi
}

echo "==> Verifying state-contractor source surfaces (filter: repo=${REPO_FILTER:-all} state=${STATE_FILTER:-all} surface=${SURFACE_FILTER:-all}, MERGE_SHA: ${MERGE_SHA:-<unset>})"

# AUDIT SUBAGENT: fill the run_surface invocations below once each state's
# upstream column list, PK, and fetch URL are locked. The placeholders below
# are intentionally non-executable (`false # AUDIT: ...`) so an unfilled
# harness FAILS LOUDLY rather than silently passing.
#
# Per-state migration verify (s1, s4, s7, s10, s13) shape:
#   cd "$APP_DIR" && doppler run -- bash -c '
#     psql "$DEX_DB_URL_DIRECT" -tAX -v ON_ERROR_STOP=1 -c "
#       SELECT 1 FROM information_schema.tables
#         WHERE table_schema = '\''entities'\''
#           AND table_name   = '\''source_state_contractor_<abbr>'\''
#     "' | grep -q '^1$'
#   PLUS column-checksum: audit records md5(string_agg(column_name||':'||data_type ORDER BY ordinal_position))
#   from information_schema.columns and the harness asserts the live schema
#   matches it byte-for-byte. (Required because directive specifies "1:1 mirror"
#   — drift in either direction is a failure.)
#   PLUS raw_source_row column existence:
#     SELECT 1 FROM information_schema.columns
#       WHERE table_schema='entities'
#         AND table_name='source_state_contractor_<abbr>'
#         AND column_name='raw_source_row' AND data_type='jsonb'
#
# Per-state code verify (s2, s5, s8, s11, s14) shape:
#   test -f "$APP_DIR/scripts/run_state_contractor_<abbr>_ingest.py"
#   python3 -c "import ast; ast.parse(open('...').read())"
#   grep -q "ON CONFLICT (license_number)"  # or whichever per-state PK column the audit picks
#   grep -q "raw_source_row" scripts/...
#   IDEMPOTENCY STRESS TEST:
#     1. Run smoke-test (e.g. --max-rows 100), capture COUNT(*) -> N1
#     2. Run smoke-test again,                  capture COUNT(*) -> N2
#     3. Assert N1 == N2 (re-running same input doesn't grow the table)
#   PLUS raw_source_row populated on every landed row:
#     SELECT COUNT(*) FROM entities.source_state_contractor_<abbr>
#       WHERE raw_source_row IS NULL  -- must be 0
#
# Per-state deploy verify (s3, s6, s9, s12, s15) shape:
#   Railway service `data-engine-x` (project `hq-all`) — confirmed via
#   `cd /Users/benjamincrane/hq-all && railway status --json`. Service watches
#   `bencrane/hq-all` main; auto-deploys on merge.
#   Production URL: https://api.dataengine.run (also data-engine-x-production.up.railway.app).
#
#   cd "$HQ_ALL" && railway status --json | jq -e --arg sha "$MERGE_SHA_PREFIX" '
#     .environments.edges[].node.serviceInstances.edges[].node
#     | select(.serviceName == "data-engine-x")
#     | .latestDeployment
#     | .status == "SUCCESS"
#       and ((.meta.commitHash // "") | startswith($sha))
#   '
#
#   PLUS scheduler-registration check — but the scheduling surface for these
#   ingests is GENUINELY UNRESOLVED in this repo (see header comment). Audit
#   MUST pick one of:
#     (a) shell-cron .sh under apps/data-engine-x/scripts/cron_state_contractor_<abbr>_refresh.sh
#         + EXPLICIT statement of which host runs the crontab (the existing
#         cron_dfpi/cron_acris/cron_nyc_hpd_dob scripts have no documented
#         host either — that's a pre-existing gap, not introduced here). Verify:
#           test -f "$APP_DIR/scripts/cron_state_contractor_<abbr>_refresh.sh"
#           bash -n "$APP_DIR/scripts/cron_state_contractor_<abbr>_refresh.sh"
#     (b) Trigger.dev task under apps/data-engine-x/trigger/src/tasks/ — but
#         no ingest task precedent exists; only enrichment/discovery tasks.
#         Per CLAUDE.md "Open boundary gap (2026-04-29)", Trigger→DEX M2M auth
#         is currently broken for new tasks. Audit must factor this in.
#     (c) Add a Railway cron service in apps/data-engine-x — no precedent in
#         hq-all; would require new Dockerfile + Railway service config.
#
# AUDIT MUST decide and document per state. The deploy verify command is then
# concrete; the placeholder below is a hard-fail until the audit fills it.

# Surface s1 — CA migration
run_surface "s1"  "bencrane/hq-all" "ca" 'false # AUDIT: fill — entities.source_state_contractor_ca table-exists + column-checksum + raw_source_row jsonb column'
# Surface s2 — CA code
run_surface "s2"  "bencrane/hq-all" "ca" 'false # AUDIT: fill — scripts/run_state_contractor_ca_ingest.py exists + parses + ON CONFLICT (license_number) + raw_source_row populated + 2-run idempotency'
# Surface s3 — CA deploy + schedule
run_surface "s3"  "bencrane/hq-all" "ca" 'false # AUDIT: fill — railway status data-engine-x latestDeployment SUCCESS at $MERGE_SHA + per-state schedule registration target'
# Surface s4 — TX migration
run_surface "s4"  "bencrane/hq-all" "tx" 'false # AUDIT: fill — entities.source_state_contractor_tx table-exists + column-checksum + raw_source_row jsonb column (TDLR: HVAC + electrical + plumbing trade-restricted licenses)'
# Surface s5 — TX code
run_surface "s5"  "bencrane/hq-all" "tx" 'false # AUDIT: fill — scripts/run_state_contractor_tx_ingest.py exists + parses + ON CONFLICT (<tx-PK>) + raw_source_row populated + 2-run idempotency'
# Surface s6 — TX deploy + schedule
run_surface "s6"  "bencrane/hq-all" "tx" 'false # AUDIT: fill — railway status data-engine-x latestDeployment SUCCESS at $MERGE_SHA + per-state schedule registration target'
# Surface s7 — FL migration
run_surface "s7"  "bencrane/hq-all" "fl" 'false # AUDIT: fill — entities.source_state_contractor_fl table-exists + column-checksum + raw_source_row jsonb column (DBPR/CILB)'
# Surface s8 — FL code
run_surface "s8"  "bencrane/hq-all" "fl" 'false # AUDIT: fill — scripts/run_state_contractor_fl_ingest.py exists + parses + ON CONFLICT (<fl-PK>) + raw_source_row populated + 2-run idempotency'
# Surface s9 — FL deploy + schedule
run_surface "s9"  "bencrane/hq-all" "fl" 'false # AUDIT: fill — railway status data-engine-x latestDeployment SUCCESS at $MERGE_SHA + per-state schedule registration target'
# Surface s10 — AZ migration
run_surface "s10" "bencrane/hq-all" "az" 'false # AUDIT: fill — entities.source_state_contractor_az table-exists + column-checksum + raw_source_row jsonb column (ROC)'
# Surface s11 — AZ code
run_surface "s11" "bencrane/hq-all" "az" 'false # AUDIT: fill — scripts/run_state_contractor_az_ingest.py exists + parses + ON CONFLICT (<az-PK>) + raw_source_row populated + 2-run idempotency'
# Surface s12 — AZ deploy + schedule
run_surface "s12" "bencrane/hq-all" "az" 'false # AUDIT: fill — railway status data-engine-x latestDeployment SUCCESS at $MERGE_SHA + per-state schedule registration target'
# Surface s13 — NC migration
run_surface "s13" "bencrane/hq-all" "nc" 'false # AUDIT: fill — entities.source_state_contractor_nc table-exists + column-checksum + raw_source_row jsonb column (NCLBGC)'
# Surface s14 — NC code
run_surface "s14" "bencrane/hq-all" "nc" 'false # AUDIT: fill — scripts/run_state_contractor_nc_ingest.py exists + parses + ON CONFLICT (<nc-PK>) + raw_source_row populated + 2-run idempotency'
# Surface s15 — NC deploy + schedule
run_surface "s15" "bencrane/hq-all" "nc" 'false # AUDIT: fill — railway status data-engine-x latestDeployment SUCCESS at $MERGE_SHA + per-state schedule registration target'

echo "==> All filtered surfaces passed."
