#!/usr/bin/env bash
# Rollback harness for directive: 2026-05-02-nppes-targeting-mvs
# Generated by audit subagent.
#
# Reverses the migration in REVERSE order of forward apply:
#   1. cron.unschedule('refresh_mv_nppes_signal_delta_new_enumerations')
#   2. cron.unschedule('refresh_mv_nppes_provider_targeting')
#   3. DROP FUNCTION ops.refresh_mv_nppes_signal_delta_new_enumerations(boolean)
#   4. DROP FUNCTION ops.refresh_mv_nppes_provider_targeting(boolean)
#   5. DROP MATERIALIZED VIEW entities.mv_nppes_signal_delta_new_enumerations CASCADE
#   6. DROP MATERIALIZED VIEW entities.mv_nppes_provider_targeting CASCADE
#
# All wrapped in a single doppler run/psql session against DEX_DB_URL_DIRECT.
# `IF EXISTS` + the `WHERE EXISTS` guard on cron.unschedule make every step
# idempotent (safe to re-run / safe to run on a partially-applied DB).
#
# No supabase_migrations.schema_migrations row to delete — apply mechanism is
# `psql -f`, not `supabase db push`, so no migrations-table row gets inserted.
#
# Git revert is post-merge: `git -C /Users/benjamincrane/Desktop/hq-all/apps/data-engine-x revert <merge-SHA>`.
#
# Usage: ./2026-05-02-nppes-targeting-mvs-rollback.sh [--surface s1] [--repo data-engine-x]

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

REPO_DIR="/Users/benjamincrane/Desktop/hq-all/apps/data-engine-x"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SQL_FILE="$SCRIPT_DIR/2026-05-02-nppes-targeting-mvs-rollback.sql"

cat > "$SQL_FILE" <<'EOF'
-- Unschedule cron jobs (no-op if absent — guarded by WHERE EXISTS).
DO $do$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'refresh_mv_nppes_signal_delta_new_enumerations') THEN
    PERFORM cron.unschedule('refresh_mv_nppes_signal_delta_new_enumerations');
  END IF;
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'refresh_mv_nppes_provider_targeting') THEN
    PERFORM cron.unschedule('refresh_mv_nppes_provider_targeting');
  END IF;
END $do$;

DROP FUNCTION IF EXISTS ops.refresh_mv_nppes_signal_delta_new_enumerations(boolean);
DROP FUNCTION IF EXISTS ops.refresh_mv_nppes_provider_targeting(boolean);

DROP MATERIALIZED VIEW IF EXISTS entities.mv_nppes_signal_delta_new_enumerations CASCADE;
DROP MATERIALIZED VIEW IF EXISTS entities.mv_nppes_provider_targeting CASCADE;
EOF

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if ( cd "$REPO_DIR" && eval "$cmd" ); then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

# Surface s1: drop both MVs, both fns, unschedule both cron jobs (in REVERSE order).
rollback_surface "s1" "data-engine-x" "doppler run -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -v ON_ERROR_STOP=1 -f $SQL_FILE'"

echo "Rollback complete."
