#!/usr/bin/env bash
# Rollback harness for directive: 2026-05-03-faa-airmen-ingest
# Generated by audit subagent.
#
# Reverses the migration in REVERSE order (s5 → s4 → s3 → s2 → s1).
#
# s5 (Modal app deploy):
#   `modal app rollback data-engine-x-faa-airmen-ingest` — first-class CLI
#   command (per `modal app rollback --help`) that redeploys the previous
#   version of the App from Modal's side. Falls back to `modal app stop` if
#   no prior version exists (first-ever deploy).
#
# s4 (Modal secret):
#   If newly created (executor recorded SECRET_PRE_EXISTED=0 in the directive's
#   ## Execution log): `modal secret delete faa-airmen-db`.
#   If pre-existing (SECRET_PRE_EXISTED=1): no-op (don't touch operator's secret).
#   Default: skip with a warning if SECRET_PRE_EXISTED is unset (destructive
#   default is unsafe).
#
# s3 + s2 (code):
#   Both files live on the merged commit. A single `git revert <merge-SHA>`
#   on bencrane/hq-all removes both. Pre-merge: don't merge.
#
# s1 (migration):
#   Surface is purely additive (new tables, no FKs out, no downstream consumers).
#   Repo convention is forward-only — no _down.sql per
#   apps/data-engine-x/supabase/migrations/README.md §"Policy". Rollback is
#   `git revert <merge-SHA>` post-merge for the migration file. For state cleanup
#   if needed: ad-hoc DROP CASCADE via dex_psql_ddl against $DEX_DB_URL_DIRECT.
#
# MERGE_SHA env var is required for s2/s3 git revert. SECRET_PRE_EXISTED env var
# (0 or 1) controls s4 behavior. Both are surfaced via standard rollback-script
# usage; callers set them based on the directive's ## Execution log.
#
# Usage:
#   MERGE_SHA=abc1234 SECRET_PRE_EXISTED=0 ./2026-05-03-faa-airmen-ingest-rollback.sh
#   ./2026-05-03-faa-airmen-ingest-rollback.sh --surface s1
#   ./2026-05-03-faa-airmen-ingest-rollback.sh --repo data-engine-x

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="/Users/benjamincrane/hq-all"
APP_DIR="$HQ_ALL/apps/data-engine-x"

# Source the shim once at top — exposes dex_psql_ddl for s1 state-cleanup path.
# shellcheck source=/dev/null
source "$HOME/Desktop/hq-all/apps/data-engine-x/scripts/migration-checks/_lib-shim.sh"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

echo "==> Rolling back faa-airmen-ingest surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

# REVERSE order: s5 → s4 → s3 → s2 → s1.

# s5 — deploy: rollback the Modal app to its previous deployed version, or stop
# the app if this was the first-ever deploy. `modal app rollback` exits non-zero
# if there's no prior version; we fall back to `modal app stop` in that case.
rollback_surface "s5" "data-engine-x" 'cd "$APP_DIR" && \
  if doppler run --project hq-all --config prd -- modal app rollback data-engine-x-faa-airmen-ingest 2>&1 | tee /tmp/faa_airmen_rollback_s5.log; then \
    echo "s5: rolled back to previous deployed version"; \
  else \
    echo "s5: rollback failed (likely first-ever deploy) — falling back to stop"; \
    doppler run --project hq-all --config prd -- modal app stop data-engine-x-faa-airmen-ingest; \
  fi'

# s4 — config: delete the Modal secret iff it did not pre-exist.
# Caller must set SECRET_PRE_EXISTED to 0 (newly created) or 1 (pre-existing).
# Unset → skip (safer than wrongly deleting a pre-existing secret).
rollback_surface "s4" "data-engine-x" 'if [[ "${SECRET_PRE_EXISTED:-unset}" == "0" ]]; then \
    doppler run --project hq-all --config prd -- modal secret delete faa-airmen-db; \
  elif [[ "${SECRET_PRE_EXISTED:-unset}" == "1" ]]; then \
    echo "s4 rollback skipped: SECRET_PRE_EXISTED=1 (pre-existing — leaving operator-owned secret intact)"; \
    true; \
  else \
    echo "s4 rollback skipped: SECRET_PRE_EXISTED unset — refusing to delete potentially-pre-existing secret. Set SECRET_PRE_EXISTED=0 or 1 explicitly to enable rollback." >&2; \
    true; \
  fi'

# s3 — code: subsumed by s2's git revert below (single revert covers both files).
rollback_surface "s3" "data-engine-x" 'echo "s3 rollback subsumed by s2 git revert (same merge SHA covers both files)" && true'

# s2 — code: open hotfix-revert PR on bencrane/hq-all and auto-merge it.
# Requires $MERGE_SHA to be set. Repo convention: hq-all auto-merges via repo
# workflow once CI is green; we use --auto so the merge happens automatically.
rollback_surface "s2" "data-engine-x" 'if [[ -z "${MERGE_SHA:-}" ]]; then echo "FAIL: MERGE_SHA env var must be set for s2/s3 rollback" >&2; exit 2; fi && \
  cd "$HQ_ALL" && \
  git fetch origin main && \
  BR="hotfix/revert-2026-05-03-faa-airmen-ingest-$(date -u +%Y%m%d-%H%M%S)" && \
  git checkout -b "$BR" origin/main && \
  git revert --no-edit "$MERGE_SHA" && \
  git push -u origin "$BR" && \
  gh -R bencrane/hq-all pr create --title "Revert: 2026-05-03-faa-airmen-ingest" --body "Auto-generated revert. Directive: /Users/benjamincrane/Desktop/hq/directives/2026-05-03-faa-airmen-ingest.md" --base main && \
  gh -R bencrane/hq-all pr merge --merge --auto --delete-branch'

# s1 — migration: revert subsumed by s2 git revert (same MERGE_SHA covers the
# migration file). For state cleanup if the migration was already applied to
# prod and you want the tables gone (additive — safe DROP CASCADE):
rollback_surface "s1" "data-engine-x" 'echo "s1 file revert subsumed by s2 git revert (same MERGE_SHA covers migration). For state cleanup, dropping tables now (additive surface):" && \
  dex_psql_ddl "DROP TABLE IF EXISTS entities.source_faa_airmen_pilot_basic CASCADE; DROP TABLE IF EXISTS entities.source_faa_airmen_pilot_cert CASCADE; DROP TABLE IF EXISTS entities.source_faa_airmen_nonpilot_basic CASCADE; DROP TABLE IF EXISTS entities.source_faa_airmen_nonpilot_cert CASCADE; DROP TABLE IF EXISTS ops.faa_airmen_ingest_runs CASCADE;"'

echo "==> Rollback complete."
