#!/usr/bin/env bash
# Rollback harness for directive: cms-irs-source-ingest-2026-05-03
# SCAFFOLD GENERATED BY VALIDATOR. Audit subagent fills per-surface DROPs.
#
# Reversal order (last applied → first rolled back):
#   s10 → s9 → s8 → s7 → s6 → s5 → s4 → s3 → s2 → s1
#
# Per-surface rollback shape:
#   migration surfaces: DROP TABLE IF EXISTS entities.source_<name> CASCADE;
#                       DROP TABLE IF EXISTS ops.<name>_ingest_runs CASCADE;
#   code surfaces:      git revert <merge-SHA>
#   pg_cron (s10):      SELECT cron.unschedule('refresh_mv_npi_signal_rollup');
#                       SELECT cron.unschedule('refresh_mv_ein_signal_rollup');
#   rollup MV (s9):     DROP MATERIALIZED VIEW IF EXISTS entities.mv_npi_signal_rollup;
#                       DROP MATERIALIZED VIEW IF EXISTS entities.mv_ein_signal_rollup;
#
# Reminder: data-engine-x has no documented down-migration policy (recon per
# validator, 2026-05-03). Audit decides whether to write paired down-migration
# .sql files in apps/data-engine-x/supabase/migrations/ alongside the up files.
#
# Usage: ./cms-irs-source-ingest-2026-05-03-rollback.sh [--repo hq-all] [--surface s1..s10]

set -euo pipefail

REPO_FILTER=""
SURFACE_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_FILTER="$2"; shift 2 ;;
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

echo "VALIDATOR SCAFFOLD — audit subagent must replace this with per-surface DROPs."
echo "Repo filter: ${REPO_FILTER:-<none>}"
echo "Surface filter: ${SURFACE_FILTER:-<all>}"
exit 0
