#!/usr/bin/env bash
# Verification harness for directive: cms-irs-source-ingest-2026-05-03
# SCAFFOLD GENERATED BY VALIDATOR. Audit subagent fills per-surface checks.
#
# Surfaces (10):
#   s1  migration  apps/data-engine-x/supabase/migrations/{ts}_open_payments_source_tables.sql
#   s2  code       apps/data-engine-x/scripts/run_open_payments_ingest.py
#   s3  migration  apps/data-engine-x/supabase/migrations/{ts}_medicare_puf_source_tables.sql
#   s4  code       apps/data-engine-x/scripts/run_medicare_physician_puf_ingest.py
#   s5  migration  apps/data-engine-x/supabase/migrations/{ts}_provider_compare_source_tables.sql
#   s6  code       apps/data-engine-x/scripts/run_provider_compare_ingest.py
#   s7  migration  apps/data-engine-x/supabase/migrations/{ts}_irs_bmf_source_tables.sql
#   s8  code       apps/data-engine-x/scripts/run_irs_bmf_ingest.py
#   s9  migration  apps/data-engine-x/supabase/migrations/{ts}_signal_rollup_mv.sql
#   s10 migration  apps/data-engine-x/supabase/migrations/{ts}_signal_rollup_pg_cron.sql
#
# NOTE FROM VALIDATOR: scope-decomposer is expected to SPLIT this directive into
# 5 sub-directives (one per source + one for the rollup MV). When that happens,
# this scaffold will be replaced by 5 per-sub-directive harnesses written by
# their respective audit subagents. Until then, this file is a placeholder so
# the directive's `## Verification harness` path resolves on disk.
#
# Usage: ./cms-irs-source-ingest-2026-05-03.sh [--repo hq-all] [--surface s1..s10]

set -euo pipefail

REPO_FILTER=""
SURFACE_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_FILTER="$2"; shift 2 ;;
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

WORKTREE="/Users/benjamincrane/hq-all/.claude/worktrees/vigorous-chatelet-f0a477"
APP_DIR="$WORKTREE/apps/data-engine-x"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

# --- Per-surface check shape (audit fills the actual SQL/grep) -------------
#
# For migration surfaces (s1, s3, s5, s7, s9, s10):
#   doppler run -p hq-all -c prd -- bash -c \
#     'psql "$DEX_DB_URL_DIRECT" -tAc "SELECT 1 FROM pg_tables WHERE schemaname=... AND tablename=..."' \
#     | grep -q 1
#
# For code surfaces (s2, s4, s6, s8):
#   test -f "$APP_DIR/scripts/run_<src>_ingest.py"
#   python3 -c "import ast; ast.parse(open('$APP_DIR/scripts/run_<src>_ingest.py').read())"
#   grep -q 'def main' "$APP_DIR/scripts/run_<src>_ingest.py"
#
# For pg_cron (s10):
#   doppler run -p hq-all -c prd -- bash -c \
#     'psql "$DEX_DB_URL_DIRECT" -tAc "SELECT count(*) FROM cron.job WHERE jobname IN (...)"' \
#     | grep -q '^2$'
#
# For the rollup MV (s9):
#   doppler run -p hq-all -c prd -- bash -c \
#     'psql "$DEX_DB_URL_DIRECT" -tAc "SELECT count(*) FROM pg_matviews WHERE schemaname=\"entities\" AND matviewname IN (...)"'
#   then post-first-refresh: SELECT count(*) > 0 from each rollup MV
#
# Reminder (CLAUDE.md, data-engine-x): always wrap doppler-injected psql in
# `bash -c '...'` to defer $-expansion. DEX_DB_URL_DIRECT for DDL/CONCURRENTLY,
# DEX_DB_URL_POOLED otherwise.
# --------------------------------------------------------------------------

echo "VALIDATOR SCAFFOLD — audit subagent must replace this with per-surface checks."
echo "Repo filter: ${REPO_FILTER:-<none>}"
echo "Surface filter: ${SURFACE_FILTER:-<all>}"
echo "App dir resolved: $APP_DIR"
exit 0
