#!/usr/bin/env bash
# Rollback harness for directive: 2026-05-11-hq-all-phase-0a-observability-foundation
# Generated by audit subagent (Stage 3.A).
#
# Reverses the 10 surfaces in REVERSE order (s10 → s9 → s8 → s7 → s6 → s5 → s4
# → s3 → s2 → s1).
#
# s10/s9/s8 (Railway redeploys):
#   Fix 4 (2026-05-12): Railway CLI 4.33.0 `railway redeploy` does NOT accept
#   --deployment-id. Verified via `railway redeploy --help`: only --service and
#   --yes are accepted. `railway deployment redeploy` is also ID-less.
#   For code rollback, git revert + push is the operative path — Railway's
#   auto-redeploy-on-merge fires on the revert commit and restores prior behavior.
#   `railway redeploy --service <name> --yes` re-triggers the LATEST deployment
#   (useful to re-run a good commit after a transient failure, NOT to pin to a
#   prior deployment ID without code changes). The s10/s9/s8 steps below issue
#   `railway redeploy --service <name> --yes` if the git revert (s2) has already
#   landed — otherwise they note that the git revert IS the rollback trigger.
#
# s7/s6/s5/s4 (code surfaces):
#   All live on the merged commit. A single `git revert <merge-SHA>` covers them.
#   Pre-merge: don't merge (no rollback needed).
#
# s3 (backfill):
#   `git revert` removes the script from the tree. State cleanup (rows in
#   ops.data_source_ingest_runs marked as migrated_from='bulk_ingest.feed_ingest_runs')
#   is the dedicated DELETE below. Safe — only deletes rows the migration created.
#
# s2 (seed):
#   `git revert` removes the script. State cleanup (rows the seed inserted) is
#   the dedicated DELETE below. Caller MUST set RUN_TS to the seed-script run
#   timestamp recorded in the directive's ## Execution log.
#
# s1 (migration):
#   Surface is purely additive (3 new tables in ops.* schema, no FKs out, no
#   existing data depends on them). Repo convention is forward-only — no
#   _down.sql per apps/data-engine-x/supabase/migrations/README.md §"Policy".
#   Rollback is `git revert <merge-SHA>` post-merge for the migration file. For
#   state cleanup if the migration was already applied to prod and you want the
#   tables gone (additive — safe DROP CASCADE):
#
# MERGE_SHA env var is required for s2-s7 git revert. RUN_TS env var is required
# for s2 row cleanup. SECRET_PRE_EXISTED is N/A here (no Modal secrets created).
#
# Usage:
#   MERGE_SHA=abc1234 RUN_TS='2026-05-12 12:34:56' ./hq-all-phase-0a-observability-foundation-rollback.sh
#   ./hq-all-phase-0a-observability-foundation-rollback.sh --surface s1
#   ./hq-all-phase-0a-observability-foundation-rollback.sh --repo data-engine-x

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="${HQ_ALL:-/Users/benjamincrane/hq-all}"
APP_DIR="$HQ_ALL/apps/data-engine-x"

# Source the shim once at top — exposes dex_psql_ddl for s1/s2/s3 state cleanup.
# shellcheck source=/dev/null
source "$HQ_ALL/apps/data-engine-x/scripts/migration-checks/_lib-shim.sh"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

echo "==> Rolling back hq-all-phase-0a-observability-foundation surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

# REVERSE order: s10 → s9 → s8 → s7 → s6 → s5 → s4 → s3 → s2 → s1.

# s10 — deploy: rollback hq-command Railway service.
# Fix 4: --deployment-id flag does not exist in railway redeploy (CLI 4.33.0).
# Git revert + merge (s2) is the operative code rollback — Railway redeploys on
# push. railway redeploy --yes re-triggers latest if needed after a transient fail.
rollback_surface "s10" "hq-command" 'echo "s10: code rollback is git revert (s2). If already merged, trigger: railway redeploy --service hq-command --yes" && true'

# s9 — deploy: rollback hq-x Railway service.
# Fix 4: see s10 note — --deployment-id flag does not exist.
rollback_surface "s9" "hq-x" 'echo "s9: code rollback is git revert (s2). If already merged, trigger: railway redeploy --service hq-x --yes" && true'

# s8 — deploy: rollback data-engine-x Railway service.
# Fix 4: see s10 note — --deployment-id flag does not exist.
rollback_surface "s8" "data-engine-x" 'echo "s8: code rollback is git revert (s2). If already merged, trigger: railway redeploy --service data-engine-x --yes" && true'

# s7 — code: hq-command page subsumed by single git revert below (same MERGE_SHA
# covers all code surfaces).
rollback_surface "s7" "hq-command" 'echo "s7 rollback subsumed by single git revert (s2 surface) — same MERGE_SHA covers all code files" && true'

# s6 — code: hq-x proxy subsumed by single git revert below.
rollback_surface "s6" "hq-x" 'echo "s6 rollback subsumed by single git revert (s2 surface)" && true'

# s5 — code: DEX endpoint subsumed by single git revert below.
rollback_surface "s5" "data-engine-x" 'echo "s5 rollback subsumed by single git revert (s2 surface)" && true'

# s4 — code: DEX service module + 3 writer touches subsumed by single git revert.
rollback_surface "s4" "data-engine-x" 'echo "s4 rollback subsumed by single git revert (s2 surface)" && true'

# s3 — code: backfill script removal subsumed by git revert. State cleanup:
# delete the migrated rows from ops.data_source_ingest_runs.
rollback_surface "s3" "data-engine-x" 'echo "s3 file revert subsumed by git revert. State cleanup: removing migrated rows from ops.data_source_ingest_runs:" && \
  dex_psql_ddl "DELETE FROM ops.data_source_ingest_runs WHERE run_metadata->>'"'"'migrated_from'"'"'='"'"'bulk_ingest.feed_ingest_runs'"'"';"'

# s2 — code: seed script removal + state cleanup. ALSO opens the single hotfix-
# revert PR on bencrane/hq-all that covers s2-s7's code surfaces.
# State cleanup: delete rows the seed inserted (created_at >= RUN_TS).
# RUN_TS must be set to the seed-script run timestamp from ## Execution log.
rollback_surface "s2" "data-engine-x" 'if [[ -z "${MERGE_SHA:-}" ]]; then echo "FAIL: MERGE_SHA env var must be set for s2-s7 git revert" >&2; exit 2; fi && \
  if [[ -n "${RUN_TS:-}" ]]; then \
    echo "s2 state cleanup: deleting ops.data_sources rows created_at >= '"'"'$RUN_TS'"'"' (and cascade their SLA + ingest-runs rows):" && \
    dex_psql_ddl "DELETE FROM ops.data_source_slas WHERE source_id IN (SELECT source_id FROM ops.data_sources WHERE created_at >= '"'"'$RUN_TS'"'"'); DELETE FROM ops.data_source_ingest_runs WHERE source_id IN (SELECT source_id FROM ops.data_sources WHERE created_at >= '"'"'$RUN_TS'"'"'); DELETE FROM ops.data_sources WHERE created_at >= '"'"'$RUN_TS'"'"';"; \
  else \
    echo "s2 state cleanup skipped: RUN_TS unset (no per-row deletion). Set RUN_TS=<seed-script-utc-timestamp> from ## Execution log to enable." >&2; \
  fi && \
  cd "$HQ_ALL" && \
  git fetch origin main && \
  BR="hotfix/revert-hq-all-phase-0a-observability-foundation-$(date -u +%Y%m%d-%H%M%S)" && \
  git checkout -b "$BR" origin/main && \
  git revert --no-edit "$MERGE_SHA" && \
  git push -u origin "$BR" && \
  gh -R bencrane/hq-all pr create --title "Revert: hq-all-phase-0a-observability-foundation" --body "Auto-generated revert. Directive: /Users/benjamincrane/Desktop/hq/directives/2026-05-11-hq-all-phase-0a-observability-foundation.md" --base main && \
  gh -R bencrane/hq-all pr merge --merge --auto --delete-branch'

# s1 — migration: file revert subsumed by s2 git revert (same MERGE_SHA covers
# the migration file). State cleanup: drop the 3 ops.* tables + 2 enums. Safe
# DROP CASCADE — additive surface, no existing data depends on them.
# CASCADE handles the FK from data_source_slas + data_source_ingest_runs to
# data_sources.
rollback_surface "s1" "data-engine-x" 'echo "s1 file revert subsumed by git revert. State cleanup: dropping ops.data_source_* tables + observability enums (safe — additive surface):" && \
  dex_psql_ddl "DROP TABLE IF EXISTS ops.data_source_ingest_runs CASCADE; DROP TABLE IF EXISTS ops.data_source_slas CASCADE; DROP TABLE IF EXISTS ops.data_sources CASCADE; DROP TYPE IF EXISTS data_source_run_status; DROP TYPE IF EXISTS data_source_sla_basis;"'

echo "==> Rollback complete."
