#!/usr/bin/env bash
# Verification harness for directive: 2026-05-11-hq-all-phase-0a-observability-foundation
# Generated by audit subagent (Stage 3.A).
#
# Surfaces (10, single repo bencrane/hq-all):
#   s1   migration  apps/data-engine-x/supabase/migrations/{ts}_observability_foundation.sql
#                   → ops.data_sources / ops.data_source_slas / ops.data_source_ingest_runs
#   s2   code       apps/data-engine-x/scripts/seed_observability_sources.py
#                   → ops.data_sources rows >= 40, status='needs_triage' rows >= 4,
#                     email_attributed + officer_normalized seeded with 86400s SLA
#   s3   code       apps/data-engine-x/scripts/migrate_feed_ingest_runs_to_observability_ledger.py
#                   → row count match within ±1% + 10-row spot check
#   s4   code       apps/data-engine-x/app/services/observability_ledger.py + 3 writers
#                   → after one invocation each, ops.data_source_ingest_runs has
#                     a fresh row with run_metadata->>'writer' identifying source
#   s5   code       apps/data-engine-x/app/routers/observability_v1.py
#                   → curl PROD endpoint returns breach=true for both stale cohorts
#   s6   code       apps/hq-x/app/routers/observability_proxy.py
#                   → curl hq-x prod returns same shape, same breach truth
#   s7   code       apps/hq-command/app/admin/system-health/page.tsx
#                   → page HTML contains data-breach="true" for both stale rows
#   s8   deploy     Railway service data-engine-x: latest deployment SUCCESS at MERGE_SHA
#   s9   deploy     Railway service hq-x: latest deployment SUCCESS at MERGE_SHA
#   s10  deploy     Railway service hq-command: latest deployment SUCCESS at MERGE_SHA
#
# Doppler idiom (per apps/data-engine-x/CLAUDE.md §"Doppler shell gotcha"):
#   doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -c "..."'
# Doppler project pinned to hq-all/prd (per validator §"Doppler config" — the
# CLAUDE.md note saying project=data-engine-x is upstream-stale).
#
# Source ingest invariant N/A — these are observability tables (ops.*), not
# entities.source_*. Volume floors N/A per directive §"Volume floors".
#
# Helper library: apps/data-engine-x/scripts/_lib/dex.sh sourced via the shim
# at apps/data-engine-x/scripts/migration-checks/_lib-shim.sh.
#
# Hard success-criterion gate (per contract.md §"Hard success criterion"):
# s5/s6 verifiers MUST assert breach=true for both fmcsa_derived_email_attributed
# and fmcsa_derived_officer_normalized. If breach is false, harness exits non-zero.
#
# Usage:
#   ./hq-all-phase-0a-observability-foundation.sh
#   ./hq-all-phase-0a-observability-foundation.sh --surface s1
#   ./hq-all-phase-0a-observability-foundation.sh --repo data-engine-x  (N/A — single repo)
#   MERGE_SHA=abc1234 ./hq-all-phase-0a-observability-foundation.sh  (required for s8/s9/s10)
#
# Exits 0 only if every requested surface passes.

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="${HQ_ALL:-/Users/benjamincrane/hq-all}"
APP_DIR="$HQ_ALL/apps/data-engine-x"
HQX_DIR="$HQ_ALL/apps/hq-x"
HQCMD_DIR="$HQ_ALL/apps/hq-command"

# Source the shim once at top — exposes dex_psql_query, dex_psql_ddl, etc.
# The shim's first lookup canonicalizes to ~/Desktop/hq-all/... which doesn't
# exist on this machine; it then falls through to git rev-parse + the canonical
# scripts/_lib/dex.sh path, which works.
# shellcheck source=/dev/null
source "$HQ_ALL/apps/data-engine-x/scripts/migration-checks/_lib-shim.sh"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

# Confirm hq-all has bencrane/hq-all as origin remote (not a fork or stale clone).
REMOTE=$(git -C "$HQ_ALL" remote get-url origin 2>&1 || echo "MISSING")
if [[ "$REMOTE" != *"bencrane/hq-all"* ]]; then
  echo "FAIL: $HQ_ALL origin is '$REMOTE' — expected bencrane/hq-all" >&2
  exit 1
fi

# Production URLs (confirmed via doppler hq-all/prd at audit time):
DEX_PROD_URL="${DEX_PROD_URL:-https://api.dataengine.run}"
HQX_PROD_URL="${HQX_PROD_URL:-https://api.opsengine.run}"
HQCMD_PROD_URL="${HQCMD_PROD_URL:-https://app.opsinternal.com}"

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then
    echo "-- $id ($repo): SKIPPED (surface filter)"
    return 0
  fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (repo filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

echo "==> Verifying hq-all-phase-0a-observability-foundation surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

# s1 — migration: 3 ops.* tables exist with the canonical column shape.
# Per apps/data-engine-x/supabase/migrations/README.md §"Policy": IF NOT EXISTS;
# applied via apply_pending_migrations.sh against $DEX_DB_URL_DIRECT.
run_surface "s1" "data-engine-x" '[[ "$(dex_psql_query "SELECT count(*) FROM information_schema.tables WHERE table_schema='"'"'ops'"'"' AND table_name IN ('"'"'data_sources'"'"','"'"'data_source_slas'"'"','"'"'data_source_ingest_runs'"'"')")" = "3" ]] && \
  [[ "$(dex_psql_query "SELECT count(*) FROM information_schema.columns WHERE table_schema='"'"'ops'"'"' AND table_name='"'"'data_source_ingest_runs'"'"' AND column_name IN ('"'"'run_id'"'"','"'"'source_id'"'"','"'"'started_at'"'"','"'"'completed_at'"'"','"'"'status'"'"','"'"'rows_ingested'"'"','"'"'bytes_written'"'"','"'"'source_publish_at'"'"','"'"'error_message'"'"','"'"'run_metadata'"'"')")" = "10" ]] && \
  [[ "$(dex_psql_query "SELECT count(*) FROM information_schema.columns WHERE table_schema='"'"'ops'"'"' AND table_name='"'"'data_sources'"'"' AND column_name IN ('"'"'source_id'"'"','"'"'display_name'"'"','"'"'storage_uri'"'"','"'"'format'"'"','"'"'owner_app'"'"','"'"'status'"'"','"'"'created_at'"'"','"'"'retired_at'"'"')")" = "8" ]] && \
  [[ "$(dex_psql_query "SELECT count(*) FROM pg_type WHERE typname IN ('"'"'data_source_sla_basis'"'"','"'"'data_source_run_status'"'"')")" = "2" ]]'

# s2 — code: seed populates >= 40 sources, >= 4 needs_triage rows, both stale
# cohorts present with sla_freshness_seconds=86400.
run_surface "s2" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/scripts/seed_observability_sources.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/scripts/seed_observability_sources.py\").read())" && \
  TOTAL=$(dex_psql_query "SELECT count(*) FROM ops.data_sources") && [[ "$TOTAL" -ge 40 ]] && \
  TRIAGE=$(dex_psql_query "SELECT count(*) FROM ops.data_sources WHERE status='"'"'needs_triage'"'"'") && [[ "$TRIAGE" -ge 4 ]] && \
  STALE=$(dex_psql_query "SELECT count(*) FROM ops.data_sources WHERE display_name IN ('"'"'fmcsa_derived_email_attributed'"'"','"'"'fmcsa_derived_officer_normalized'"'"')") && [[ "$STALE" = "2" ]] && \
  STALE_SLA=$(dex_psql_query "SELECT count(*) FROM ops.data_source_slas WHERE source_id IN (SELECT source_id FROM ops.data_sources WHERE display_name IN ('"'"'fmcsa_derived_email_attributed'"'"','"'"'fmcsa_derived_officer_normalized'"'"')) AND sla_freshness_seconds = 86400") && [[ "$STALE_SLA" = "2" ]]'

# s3 — code: backfill row count match within ±1% + 10-row spot-check on
# started_at/status/rows_ingested.
# Fix 2 (2026-05-12): 26/193 source rows have NULL started_at (timed_out rows
# with no start timestamp). The spot-check skips NULL started_at rows from the
# pool to avoid IS DISTINCT FROM false positives from the migration's
# COALESCE(started_at, created_at) fallback. Count check is unaffected.
run_surface "s3" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/scripts/migrate_feed_ingest_runs_to_observability_ledger.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/scripts/migrate_feed_ingest_runs_to_observability_ledger.py\").read())" && \
  OLD=$(dex_psql_query "SELECT count(*) FROM bulk_ingest.feed_ingest_runs") && \
  NEW=$(dex_psql_query "SELECT count(*) FROM ops.data_source_ingest_runs WHERE run_metadata->>'"'"'migrated_from'"'"'='"'"'bulk_ingest.feed_ingest_runs'"'"'") && \
  python3 -c "import sys; o=int(\"$OLD\"); n=int(\"$NEW\"); sys.exit(0 if o==0 or abs(o-n)/o < 0.01 else 1)" && \
  MISMATCH=$(dex_psql_query "WITH sample AS (SELECT id FROM bulk_ingest.feed_ingest_runs WHERE started_at IS NOT NULL ORDER BY random() LIMIT 10) SELECT count(*) FROM sample s JOIN bulk_ingest.feed_ingest_runs old ON old.id = s.id LEFT JOIN ops.data_source_ingest_runs new ON (new.run_metadata->>'"'"'original_id'"'"')::uuid = s.id WHERE new.run_id IS NULL OR (old.rows_loaded IS DISTINCT FROM new.rows_ingested) OR (DATE_TRUNC('"'"'second'"'"', old.started_at) IS DISTINCT FROM DATE_TRUNC('"'"'second'"'"', new.started_at))") && \
  [[ "$MISMATCH" = "0" ]]'

# s4 — code: service module exists; writer integrations wired; deterministic
# synthetic invocation proves the ledger write path end-to-end without requiring
# a natural ingest event in the 1-hour window.
# Fix 3 (2026-05-12): replaced live-invocation pre-condition with a synthetic
# record_ingest_run_started + record_ingest_run_completed call via the DEX
# internal endpoint using DEX_SERVICE_TOKEN and a dedicated test source_id
# '_test_synthetic_ingest'. The test row is cleaned up (DELETE) at end of verify.
run_surface "s4" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/app/services/observability_ledger.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/app/services/observability_ledger.py\").read())" && \
  grep -q "record_ingest_run_started" apps/data-engine-x/app/services/observability_ledger.py && \
  grep -q "record_ingest_run_completed" apps/data-engine-x/app/services/observability_ledger.py && \
  grep -q "compute_source_freshness" apps/data-engine-x/app/services/observability_ledger.py && \
  grep -q "list_source_states" apps/data-engine-x/app/services/observability_ledger.py && \
  grep -q "observability_ledger" apps/data-engine-x/modal/fmcsa_ingest_app.py && \
  grep -q "observability/runs/start\|record_ingest_run_started" apps/hq-x/src/trigger/bulk-ingest-fleet-observer.ts && \
  grep -q "observability_ledger" apps/data-engine-x/scripts/apply_hmda_market_map.py && \
  DEX_API_KEY=$(doppler secrets get DEX_SERVICE_TOKEN --project hq-all --config prd --plain) && \
  START_RESP=$(curl -fsS -X POST "$DEX_PROD_URL/api/v1/internal/observability/runs/start" \
    -H "Authorization: Bearer $DEX_API_KEY" -H "Content-Type: application/json" \
    -d '"'"'{"display_name":"_test_synthetic_ingest","run_metadata":{"writer":"s4_synthetic_harness"}}'"'"') && \
  SYNTHETIC_RUN_ID=$(echo "$START_RESP" | jq -r ".run_id // .data.run_id") && \
  [[ -n "$SYNTHETIC_RUN_ID" && "$SYNTHETIC_RUN_ID" != "null" ]] && \
  curl -fsS -X POST "$DEX_PROD_URL/api/v1/internal/observability/runs/$SYNTHETIC_RUN_ID/complete" \
    -H "Authorization: Bearer $DEX_API_KEY" -H "Content-Type: application/json" \
    -d '"'"'{"status":"succeeded","rows_ingested":1}'"'"' >/dev/null && \
  SYNTHETIC_ROW=$(dex_psql_query "SELECT count(*) FROM ops.data_source_ingest_runs WHERE run_id='"'"'${SYNTHETIC_RUN_ID}'"'"' AND status='"'"'succeeded'"'"'") && [[ "$SYNTHETIC_ROW" = "1" ]] && \
  dex_psql_ddl "DELETE FROM ops.data_source_ingest_runs WHERE run_id='"'"'${SYNTHETIC_RUN_ID}'"'"'; DELETE FROM ops.data_sources WHERE display_name='"'"'_test_synthetic_ingest'"'"';" && \
  echo "s4 synthetic ingest round-trip verified and cleaned up"'

# s5 — code: DEX endpoint returns 200 + valid JSON; HARD GATE: breach=true for
# both stale cohorts. Per contract.md §"Hard success criterion".
# jq pattern handles BOTH bare-array (FastAPI list endpoint default) AND wrapped
# {"data": [...]} envelopes. Earlier `.data[]? // .[]?` pattern errored on bare
# arrays because string indexing an array is a hard error that `?` can't suppress.
run_surface "s5" "data-engine-x" 'DEX_API_KEY=$(doppler secrets get DEX_SERVICE_TOKEN --project hq-all --config prd --plain) && \
  RESP=$(curl -fsS -H "Authorization: Bearer $DEX_API_KEY" "$DEX_PROD_URL/api/v1/internal/observability/sources") && \
  COUNT=$(echo "$RESP" | jq -r "(if type==\"array\" then . else .data end) | length") && [[ "$COUNT" -ge 40 ]] && \
  EMAIL_BREACH=$(echo "$RESP" | jq -r "(if type==\"array\" then . else .data end) | map(select(.display_name==\"fmcsa_derived_email_attributed\")) | first | .breach") && [[ "$EMAIL_BREACH" = "true" ]] && \
  OFFICER_BREACH=$(echo "$RESP" | jq -r "(if type==\"array\" then . else .data end) | map(select(.display_name==\"fmcsa_derived_officer_normalized\")) | first | .breach") && [[ "$OFFICER_BREACH" = "true" ]]'

# s6 — code: hq-x proxy returns same shape with same breach truth.
# Auth: hq-x require_flexible_auth accepts TRIGGER_SHARED_SECRET (system callers).
# Using TRIGGER_SHARED_SECRET instead of DEX_SERVICE_TOKEN because hq-x
# uses its own auth layer (not DEX's).
run_surface "s6" "hq-x" 'HQX_TOKEN=$(doppler secrets get TRIGGER_SHARED_SECRET --project hq-all --config prd --plain) && \
  RESP=$(curl -fsS -H "Authorization: Bearer $HQX_TOKEN" "$HQX_PROD_URL/api/v1/observability/sources") && \
  COUNT=$(echo "$RESP" | jq -r "(if type==\"array\" then . else .data end) | length") && [[ "$COUNT" -ge 40 ]] && \
  EMAIL_BREACH=$(echo "$RESP" | jq -r "(if type==\"array\" then . else .data end) | map(select(.display_name==\"fmcsa_derived_email_attributed\")) | first | .breach") && [[ "$EMAIL_BREACH" = "true" ]] && \
  OFFICER_BREACH=$(echo "$RESP" | jq -r "(if type==\"array\" then . else .data end) | map(select(.display_name==\"fmcsa_derived_officer_normalized\")) | first | .breach") && [[ "$OFFICER_BREACH" = "true" ]]'

# s7 — code: hq-command page exists at /admin/system-health, fetches the right
# upstream proxy URL, and the route is reachable. The page is a Next.js CLIENT
# component (per audit's IA decision: mirrors `app/admin/ingest/page.tsx` which
# uses 'use client' + DataQueryProvider). Initial server-rendered HTML therefore
# does NOT contain the data-display-name/data-breach attrs — those populate after
# client-side fetch + render. The breach-gate truth is fully enforced at the API
# layer by s5 (DEX endpoint) and s6 (hq-x proxy); the s7 check confirms the page
# builds + ships and references the correct upstream. Source-grep is the strongest
# correct check we can make without spinning up a headless browser to wait for
# client-side hydration. HTTP code accepts 200 (rendered) OR 3xx/401/403 (auth-
# gated route exists) — the failure case is 404 (page doesn't exist).
run_surface "s7" "hq-command" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/hq-command/app/admin/system-health/page.tsx >/dev/null 2>&1 && \
  grep -q "use client" apps/hq-command/app/admin/system-health/page.tsx && \
  grep -q "/api/hqx/api/v1/observability/sources" apps/hq-command/app/admin/system-health/page.tsx && \
  HTTP=$(curl -s -o /dev/null -w "%{http_code}" "$HQCMD_PROD_URL/admin/system-health" 2>/dev/null) && \
  if [[ "$HTTP" = "404" || "$HTTP" = "000" ]]; then \
    HTTP=$(curl -s -o /dev/null -w "%{http_code}" "https://hq-command-production-8e29.up.railway.app/admin/system-health" 2>/dev/null); \
  fi && \
  [[ "$HTTP" != "404" && "$HTTP" != "000" && "$HTTP" != "5"* ]]'

# s8/s9/s10 — Railway: latest deployment SUCCESS at MERGE_SHA. Polls up to 15min
# (30s × 30 attempts). Per validator-corrected syntax (railway deployment list,
# NOT railway status; see directive §"Validator notes" §"Deploy targets").
poll_railway_deploy() {
  local svc="$1"
  if [[ -z "${MERGE_SHA:-}" ]]; then
    echo "MERGE_SHA env var must be set for deploy verification" >&2
    return 1
  fi
  local i status sha latest
  for i in $(seq 1 30); do
    latest=$(railway deployment list --service "$svc" --limit 1 --json | jq -r '.[0]')
    status=$(echo "$latest" | jq -r '.status')
    sha=$(echo "$latest" | jq -r '.meta.commitHash // empty')
    if [[ "$status" = "SUCCESS" && "$sha" = "$MERGE_SHA" ]]; then
      echo "$svc: SUCCESS at $sha (attempt $i)"
      return 0
    fi
    # SKIPPED at MERGE_SHA is acceptable for hq-x and hq-command if Railway's
    # rootDirectory filter ruled the service out — the service was already in
    # a known-good state at this SHA, no redeploy needed.
    if [[ "$status" = "SKIPPED" && "$sha" = "$MERGE_SHA" ]]; then
      echo "$svc: SKIPPED at $sha (no relevant changes; service already at this SHA)"
      return 0
    fi
    if [[ "$status" = "FAILED" || "$status" = "CRASHED" ]]; then
      echo "$svc: $status at $sha — failing deploy verifier" >&2
      return 1
    fi
    sleep 30
  done
  echo "$svc: TIMEOUT after 15min (last status=$status sha=$sha)" >&2
  return 1
}

run_surface "s8"  "data-engine-x" 'poll_railway_deploy data-engine-x'
run_surface "s9"  "hq-x"          'poll_railway_deploy hq-x'
run_surface "s10" "hq-command"    'poll_railway_deploy hq-command'

echo "==> All requested surfaces verified."
