#!/usr/bin/env bash
# Rollback harness for directive: mv-nppes-type2-external-matches (2026-05-03).
# Generated by /scope audit subagent.
#
# Reverses surfaces in REVERSE order of forward apply:
#
#   s2 (deploy)  — DOCUMENTED, NOT auto-executed. The primary deploy-rollback
#                  path is a revert PR which Railway auto-deploys on merge.
#                  `railway down --service data-engine-x --yes` is reserved for
#                  emergency-stop and would leave the service offline until a
#                  new deploy lands; this harness intentionally does NOT run it.
#
#   s1 (DB)      — DROP MATERIALIZED VIEW IF EXISTS entities.mv_nppes_type2_external_matches CASCADE.
#                  Idempotent (IF EXISTS), safe to re-run on already-dropped state.
#                  No `_DOWN.sql` sibling was added per the data-engine-x
#                  forward-only convention; the rollback IS this command.
#                  No supabase_migrations.schema_migrations row to delete —
#                  apply mechanism is `psql -f`, not `supabase db push`.
#
# Usage:
#   ./mv-nppes-type2-external-matches-rollback.sh                                # all surfaces
#   ./mv-nppes-type2-external-matches-rollback.sh --surface s1                   # DB rollback only
#   ./mv-nppes-type2-external-matches-rollback.sh --surface s2                   # documents deploy path
#   ./mv-nppes-type2-external-matches-rollback.sh --repo bencrane/hq-all         # filter (no-op)
#
# Exits 0 iff the requested rollback steps complete; non-zero on the first failure.

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

REPO_DIR="/Users/benjamincrane/hq-all/apps/data-engine-x"

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if ( cd "$REPO_DIR" && eval "$cmd" ); then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

# -----------------------------------------------------------------------------
# s2 first (REVERSE order). Deploy rollback is post-merge revert PR; this
# harness only documents the path — no auto-execution.
# -----------------------------------------------------------------------------
if [[ -z "$SURFACE_FILTER" || "$SURFACE_FILTER" == "s2" ]]; then
  if [[ -z "$REPO_FILTER" || "$REPO_FILTER" == "bencrane/hq-all" ]]; then
    cat <<'NOTE'
-- rollback s2 (bencrane/hq-all): DOCUMENTED, NOT auto-executed.
   Primary path:
     1. Revert the merge commit on bencrane/hq-all main:
          git -C /Users/benjamincrane/hq-all revert <merge-SHA>
        Push the revert; Railway auto-deploys it (~2-3 min) and the
        previous container image takes traffic again.
     2. Then run: ./mv-nppes-type2-external-matches-rollback.sh --surface s1
        to drop the MV from the prod DB.
   Emergency-stop only (leaves service offline until next deploy):
          cd /Users/benjamincrane/hq-all/apps/data-engine-x && railway down --service data-engine-x --yes
NOTE
  fi
fi

# -----------------------------------------------------------------------------
# s1 last. DB-side drop of the MV.
# -----------------------------------------------------------------------------
rollback_surface "s1" "bencrane/hq-all" 'doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -v ON_ERROR_STOP=1 -c "DROP MATERIALIZED VIEW IF EXISTS entities.mv_nppes_type2_external_matches CASCADE;"'"'"

echo "Rollback complete."
