#!/usr/bin/env bash
# Verification harness for directive: mv-nppes-type2-external-matches (2026-05-03).
# Generated by /scope audit subagent.
#
# Asserts the post-apply state of supabase/migrations/20260503170000_mv_nppes_type2_external_matches.sql:
#
#   s1.a — entities.mv_nppes_type2_external_matches exists in pg_matviews and is populated.
#   s1.b — row count > 0.
#   s1.c — per-source counts: pdl > 0, sam > 0, overture = 0; no source values outside the
#          reserved enum {'pdl','sam','overture'}.
#   s1.d — every nppes_npi joins back to entities.nppes_providers with
#          entity_type_code = 2 AND (npi_deactivation_date IS NULL OR > CURRENT_DATE).
#   s1.e — schema columns match spec exactly:
#          (nppes_npi:text, source:text, source_id:text, match_signal:text, match_confidence:numeric).
#   s1.f — every populated source carries every declared match_signal value
#          (currently a single literal 'name_state').
#
#   s2.a — Railway deploy status is SUCCESS for the data-engine-x service in the hq-all
#          project, and the deployed commit hash matches the merge SHA.
#          Executor sets MERGE_SHA=<sha> in the env (or it defaults to origin/main HEAD).
#   s2.b — re-runs every s1.* check against the deployed prod DB. (Same harness; no-op here.)
#   s2.c — HTTP smoke layer: curl -fsS https://api.dataengine.run/health.
#
# All DB checks use the Doppler subshell idiom (per apps/data-engine-x/CLAUDE.md
# §"Doppler Shell Gotcha") so $DEX_DB_URL_DIRECT is expanded INSIDE the doppler-injected
# subshell rather than the local shell.
#
# Single-quoted commands defer all $VAR interpolation to runtime.
#
# Usage:
#   ./mv-nppes-type2-external-matches.sh                         # all checks
#   ./mv-nppes-type2-external-matches.sh --repo bencrane/hq-all  # filter (no-op for single-repo)
#
# Exits 0 iff every requested check passes; non-zero on the first failure.

set -euo pipefail

REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

REPO_DIR="/Users/benjamincrane/hq-all/apps/data-engine-x"

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if ( cd "$REPO_DIR" && eval "$cmd" ); then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

echo "==> Verifying mv-nppes-type2-external-matches (filter: ${REPO_FILTER:-all})"

# ---------------------------------------------------------------------------
# s1 sub-checks (DB-side, against DEX_DB_URL_DIRECT)
# ---------------------------------------------------------------------------

# s1.a — MV exists in entities schema and is populated.
run_surface "s1.a" "bencrane/hq-all" 'result=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -v ON_ERROR_STOP=1 -c "SELECT COUNT(*)=1 FROM pg_matviews WHERE schemaname='"'"'"'"'"'"'"'"'entities'"'"'"'"'"'"'"'"' AND matviewname='"'"'"'"'"'"'"'"'mv_nppes_type2_external_matches'"'"'"'"'"'"'"'"' AND ispopulated;"'"'"') && [[ "$result" == "t" ]]'

# s1.b — row count > 0.
run_surface "s1.b" "bencrane/hq-all" 'result=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -v ON_ERROR_STOP=1 -c "SELECT COUNT(*)>0 FROM entities.mv_nppes_type2_external_matches;"'"'"') && [[ "$result" == "t" ]]'

# s1.c — per-source counts: pdl>0, sam>0, overture=0; no source values outside the reserved enum.
run_surface "s1.c" "bencrane/hq-all" 'result=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -v ON_ERROR_STOP=1 -c "SELECT (SELECT COUNT(*) FROM entities.mv_nppes_type2_external_matches WHERE source='"'"'"'"'"'"'"'"'pdl'"'"'"'"'"'"'"'"')>0 AND (SELECT COUNT(*) FROM entities.mv_nppes_type2_external_matches WHERE source='"'"'"'"'"'"'"'"'sam'"'"'"'"'"'"'"'"')>0 AND (SELECT COUNT(*) FROM entities.mv_nppes_type2_external_matches WHERE source='"'"'"'"'"'"'"'"'overture'"'"'"'"'"'"'"'"')=0 AND NOT EXISTS (SELECT 1 FROM entities.mv_nppes_type2_external_matches WHERE source NOT IN ('"'"'"'"'"'"'"'"'pdl'"'"'"'"'"'"'"'"','"'"'"'"'"'"'"'"'sam'"'"'"'"'"'"'"'"','"'"'"'"'"'"'"'"'overture'"'"'"'"'"'"'"'"'));"'"'"') && [[ "$result" == "t" ]]'

# s1.d — every nppes_npi satisfies the LHS filter on entities.nppes_providers.
run_surface "s1.d" "bencrane/hq-all" 'result=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -v ON_ERROR_STOP=1 -c "SELECT NOT EXISTS (SELECT 1 FROM entities.mv_nppes_type2_external_matches m LEFT JOIN entities.nppes_providers p ON p.npi::text = m.nppes_npi WHERE p.npi IS NULL OR p.entity_type_code <> 2 OR (p.npi_deactivation_date IS NOT NULL AND p.npi_deactivation_date <= CURRENT_DATE));"'"'"') && [[ "$result" == "t" ]]'

# s1.e — schema columns match spec exactly.
run_surface "s1.e" "bencrane/hq-all" 'result=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -v ON_ERROR_STOP=1 -c "SELECT string_agg(column_name || '"'"'"'"'"'"'"'"':'"'"'"'"'"'"'"'"' || data_type, '"'"'"'"'"'"'"'"','"'"'"'"'"'"'"'"' ORDER BY ordinal_position) FROM information_schema.columns WHERE table_schema='"'"'"'"'"'"'"'"'entities'"'"'"'"'"'"'"'"' AND table_name='"'"'"'"'"'"'"'"'mv_nppes_type2_external_matches'"'"'"'"'"'"'"'"';"'"'"') && [[ "$result" == "nppes_npi:text,source:text,source_id:text,match_signal:text,match_confidence:numeric" ]]'

# s1.f — every populated source carries every declared match_signal (currently {'name_state'}).
run_surface "s1.f" "bencrane/hq-all" 'result=$(doppler run -- bash -c '"'"'psql "$DEX_DB_URL_DIRECT" -tAX -v ON_ERROR_STOP=1 -c "SELECT NOT EXISTS (SELECT s.source FROM (VALUES ('"'"'"'"'"'"'"'"'pdl'"'"'"'"'"'"'"'"'),('"'"'"'"'"'"'"'"'sam'"'"'"'"'"'"'"'"')) AS s(source) WHERE NOT EXISTS (SELECT 1 FROM entities.mv_nppes_type2_external_matches m WHERE m.source = s.source AND m.match_signal = '"'"'"'"'"'"'"'"'name_state'"'"'"'"'"'"'"'"'));"'"'"') && [[ "$result" == "t" ]]'

# ---------------------------------------------------------------------------
# s2 sub-checks (deploy-side)
# ---------------------------------------------------------------------------
# s2.a — Railway deploy status SUCCESS + commit hash matches.
#        MERGE_SHA may be passed via env; default to origin/main HEAD.
#        Railway returns 12-char short OR 40-char long commitHash; we
#        symmetric-prefix-match with a 12-char minimum-length floor on BOTH
#        sides so an empty commit field can never satisfy the match.
run_surface "s2.a" "bencrane/hq-all" 'expected="${MERGE_SHA:-$(git -C /Users/benjamincrane/hq-all rev-parse origin/main)}" && line=$(railway status --json | jq -r '"'"'.environments.edges[] | select(.node.name=="production") | .node.serviceInstances.edges[] | select(.node.serviceName=="data-engine-x") | "\(.node.latestDeployment.status)\t\(.node.latestDeployment.meta.commitHash)"'"'"') && status=$(echo "$line" | cut -f1) && commit=$(echo "$line" | cut -f2) && [[ "$status" == "SUCCESS" ]] && [[ ${#expected} -ge 12 && ${#commit} -ge 12 ]] && [[ "$expected" == "$commit"* || "$commit" == "$expected"* ]]'

# s2.b — already covered by re-running s1.* checks above against the deployed prod DB.
echo "-- s2.b (bencrane/hq-all): covered by s1.a-s1.f re-runs; no separate assertion."

# s2.c — HTTP smoke layer.
run_surface "s2.c" "bencrane/hq-all" 'curl -fsS -o /dev/null -w "%{http_code}" https://api.dataengine.run/health | grep -qx "200"'

# ---------------------------------------------------------------------------
# Sanity prints (informational only — do not affect exit code).
# ---------------------------------------------------------------------------
echo "==> Sanity counts:"
( cd "$REPO_DIR" && doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT '\''mv rows='\'' || COUNT(*) FROM entities.mv_nppes_type2_external_matches;"' || true )
( cd "$REPO_DIR" && doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT source, COUNT(*) FROM entities.mv_nppes_type2_external_matches GROUP BY 1 ORDER BY 1;"' || true )
( cd "$REPO_DIR" && doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -tAX -c "SELECT match_signal, COUNT(*) FROM entities.mv_nppes_type2_external_matches GROUP BY 1 ORDER BY 1;"' || true )

echo "All requested surfaces verified."
