#!/usr/bin/env bash
# Rollback harness for directive: 2026-05-03-promote-sam-entity-url-resolution
# Generated by audit subagent; quoting fixed by reviewer (2026-05-03).
#
# Reverses surfaces in REVERSE order of forward apply.
#
# Forward order: s1 (CREATE MV) → s2 (CREATE INDEXES) → s3 (deploy).
# Reverse order: s3 (no DB action; redeploy via dashboard if needed) →
#                s2 (indexes drop with MV via CASCADE) →
#                s1 (DROP MATERIALIZED VIEW IF EXISTS ... CASCADE).
#
# Per the directive's "## Deploy targets" section, Railway CLI v4 cannot
# rollback to a historic deployment by ID — rollback is dashboard-only.
# Therefore s3 has no CLI rollback action; the executor's recovery for a
# bad deploy is: (1) DROP the MV via this script; (2) git revert the merge
# SHA in bencrane/hq-all; (3) auto-redeploy on revert merge.
#
# Both s1 and s2 collapse to a single DROP MATERIALIZED VIEW — the
# partial-unique indexes attach to the MV and drop with it (CASCADE used
# for safety; pre-rollback dependent-objects check warns before dropping
# anything unexpected).
#
# Idempotent: IF EXISTS guard makes every run safe.
#
# Usage:
#   ./promote-sam-entity-url-resolution-rollback.sh [--surface s1|s2|s3] [--repo bencrane/hq-all]

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

REPO="bencrane/hq-all"
TMPDIR="$(mktemp -d -t promote-sam-entity-url-resolution-rollback.XXXXXX)"
trap 'rm -rf "$TMPDIR"' EXIT

# Pre-rollback dependent-objects check. If any view/MV depends on
# entities.mv_resolved_website, CASCADE would drop them. By directive design
# there should be no consumers at this stage; if any exist, warn loudly and
# abort so an operator can review.
cat > "$TMPDIR/dep_check.sql" <<'SQL'
SELECT count(*) FROM pg_depend d
JOIN pg_class c ON c.oid = d.objid
JOIN pg_class r ON r.oid = d.refobjid
WHERE r.relname = 'mv_resolved_website'
  AND c.relkind IN ('m','v')
  AND d.deptype = 'n';
SQL

cat > "$TMPDIR/drop.sql" <<'SQL'
DROP MATERIALIZED VIEW IF EXISTS entities.mv_resolved_website CASCADE;
SQL

pre_rollback_check_no_dependents() {
  local count
  count=$(doppler run -p data-engine-x -c prd -- bash -c "psql \"\$DEX_DB_URL_DIRECT\" -tAX -v ON_ERROR_STOP=1 -f $TMPDIR/dep_check.sql" 2>/dev/null | tr -d '[:space:]')
  if [[ "${count:-0}" -gt 0 ]]; then
    echo "WARNING: $count dependent object(s) exist on entities.mv_resolved_website. CASCADE will drop them. Aborting rollback — review manually." >&2
    return 1
  fi
  return 0
}

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

# s3 rollback: no CLI action available. Operator must trigger Railway
# dashboard rollback OR git revert + auto-redeploy. This stub records
# intent and exits 0 so the harness can proceed to s2/s1 DB rollback.
rollback_surface "s3" "$REPO" \
  'echo "  (s3) Railway CLI v4 cannot rollback to a historic deployment by ID; use dashboard or git revert + auto-redeploy. No CLI action."'

# s2 rollback: indexes drop with MV via CASCADE — collapses into s1.
rollback_surface "s2" "$REPO" \
  'echo "  (s2) Indexes are dropped by s1 CASCADE; no separate action."'

# s1 rollback: pre-check for dependents, then DROP MATERIALIZED VIEW IF EXISTS ... CASCADE.
rollback_surface "s1" "$REPO" \
  "pre_rollback_check_no_dependents && doppler run -p data-engine-x -c prd -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -v ON_ERROR_STOP=1 -f $TMPDIR/drop.sql'"

echo "Rollback complete."
echo "Reminder: post-merge / post-deploy rollback also requires:"
echo "  git -C /Users/benjamincrane/Desktop/hq-all revert <merge-SHA>"
echo "  git -C /Users/benjamincrane/Desktop/hq-all push origin main"
