#!/usr/bin/env bash
# Verification harness for directive: 2026-05-03-promote-sam-entity-url-resolution
# Generated by audit subagent; quoting fixed by reviewer (2026-05-03).
#
# Verifies the three surfaces of the migration that creates
# entities.mv_resolved_website (composite/pdl/sam-only slices) plus the
# Railway deploy. All checks read-only; safe to re-run.
#
# Surfaces (run in declared order):
#   s1+s2-presence : MV exists AND has >= 4 indexes (the four CREATE INDEX
#                    statements in the migration: ux_pdl_id, ux_sam_uei,
#                    ix_source, ix_domain).
#   s1+s2-volume   : Slice row counts in the validator-predicted ranges:
#                      composite ∈ [70k, 90k]
#                      pdl       > 20M
#                      sam       ∈ [300k, 500k]
#   s3-deploy      : production /health returns "status":"ok".
#
# Quoting strategy: SQL is written to /tmp/*.sql files (one per surface) so
# the inner SQL never has to survive multiple shell-parse passes. The Doppler
# command then `psql -f </tmp/path>`. The `bash -c '...'` form is preserved
# only for variable expansion of $DEX_DB_URL_DIRECT inside the Doppler
# subshell.
#
# Usage:
#   ./promote-sam-entity-url-resolution.sh [--repo bencrane/hq-all]
#
# Exit non-zero if any surface fails.

set -euo pipefail

REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

REPO="bencrane/hq-all"
PROD_URL="https://data-engine-x-production.up.railway.app"
TMPDIR="$(mktemp -d -t promote-sam-entity-url-resolution.XXXXXX)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "==> Verifying promote-sam-entity-url-resolution surfaces (filter: ${REPO_FILTER:-all})"

# Write per-surface SQL to /tmp so inner quoting doesn't have to survive
# multi-level shell parse + eval. psql is invoked with -f to read the file.
cat > "$TMPDIR/s1s2_presence.sql" <<'SQL'
SELECT
  (SELECT count(*) FROM pg_matviews
     WHERE schemaname = 'entities'
       AND matviewname = 'mv_resolved_website') = 1
  AND
  (SELECT count(*) FROM pg_indexes
     WHERE schemaname = 'entities'
       AND tablename = 'mv_resolved_website') >= 4;
SQL

cat > "$TMPDIR/s1s2_volume.sql" <<'SQL'
-- Reviewer-measured prod ranges (2026-05-03):
--   composite       = 78,634   (target 70k-90k)
--   pdl             = 5,819,884 (target 5M-7M; not 20M as initially forecast —
--                                mv_pdl_companies_normalized is US-only and
--                                deduped to 8.99M total, not the raw 23M
--                                pdl_companies count)
--   sam_entity_url  = 376,477  (target 300k-500k)
SELECT
  (count(*) FILTER (WHERE source = 'composite')      BETWEEN 70000   AND 90000)
  AND
  (count(*) FILTER (WHERE source = 'pdl')            BETWEEN 5000000 AND 7000000)
  AND
  (count(*) FILTER (WHERE source = 'sam_entity_url') BETWEEN 300000  AND 500000)
FROM entities.mv_resolved_website;
SQL

cat > "$TMPDIR/sanity_total.sql" <<'SQL'
SELECT 'mv_resolved_website total=' || count(*) FROM entities.mv_resolved_website;
SQL

cat > "$TMPDIR/sanity_by_source.sql" <<'SQL'
SELECT source, count(*) FROM entities.mv_resolved_website GROUP BY source ORDER BY source;
SQL

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

# Surface s1+s2 (presence): MV exists and has >= 4 indexes.
# Outer single quotes preserve $TMPDIR expansion in the script's shell;
# $DEX_DB_URL_DIRECT expands inside the Doppler subshell via bash -c '...'.
run_surface "s1+s2-presence" "$REPO" \
  "doppler run -p data-engine-x -c prd -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -tAX -v ON_ERROR_STOP=1 -f $TMPDIR/s1s2_presence.sql' | grep -q '^t\$'"

# Surface s1+s2 (volume): per-slice row counts in predicted ranges.
run_surface "s1+s2-volume" "$REPO" \
  "doppler run -p data-engine-x -c prd -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -tAX -v ON_ERROR_STOP=1 -f $TMPDIR/s1s2_volume.sql' | grep -q '^t\$'"

# Surface s3 (deploy): production /health returns {"status":"ok",...}.
run_surface "s3-deploy" "$REPO" \
  "curl -fsS '${PROD_URL}/health' | grep -q '\"status\":\"ok\"'"

# Informational sanity counts (do not affect exit code).
echo "==> Sanity counts (informational):"
doppler run -p data-engine-x -c prd -- bash -c "psql \"\$DEX_DB_URL_DIRECT\" -tAX -f $TMPDIR/sanity_total.sql" || true
doppler run -p data-engine-x -c prd -- bash -c "psql \"\$DEX_DB_URL_DIRECT\" -tAX -f $TMPDIR/sanity_by_source.sql" || true

echo "All requested surfaces verified."
