#!/usr/bin/env bash
# Rollback harness for /scope cycle sec-8k-item-203-extension.
#
# Runs surface rollbacks in REVERSE order (s7 → s1).
#
# Forward-only migrations: code/config/migration rollback is "git revert <merge-SHA>"
# applied post-merge. The script encodes the deployable-state rollbacks (Modal app
# stop, ops.data_sources retire, Lance prefix deletion); the source-revert is a
# separate operator-driven step (orchestrator step 4c, hotfix-revert PR).
#
# Usage:
#   ./sec-8k-item-203-extension-rollback.sh                          # all surfaces
#   ./sec-8k-item-203-extension-rollback.sh --surface s7              # single surface
#   ./sec-8k-item-203-extension-rollback.sh --repo hq-all             # single repo (no-op; single repo)
#
# Generated by Stage 3.A audit for directive
# ~/Desktop/hq/directives/2026-05-12-sec-8k-item-203-extension.md
set -euo pipefail

# shellcheck source=./_lib-shim.sh
source "$(dirname "$0")/_lib-shim.sh"

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

echo "==> Rolling back surfaces for sec-8k-item-203-extension (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

# REVERSE order — last surface rolled back first.

# s7 — Modal cron: stop the app
rollback_surface "s7" "hq-all" '
  cd ~/hq-all/apps/data-engine-x && \
  doppler run --project hq-all --config prd -- modal app stop data-engine-x-sec-edgar-form-8k
'

# s6 — ops.data_sources: retire both rows
rollback_surface "s6" "hq-all" '
  dex_psql_ddl "UPDATE ops.data_sources SET status='\''retired'\'' WHERE display_name IN ('\''sec_edgar_form_8k'\'', '\''sec_edgar_form_8k_lance'\'')"
'

# s5 — Lance prefix: delete from R2 (derivative dataset)
rollback_surface "s5" "hq-all" '
  doppler run --project hq-all --config prd -- bash -c '\''
    aws s3 rm s3://dex-raw-landing-zone/polaris-warehouse/sec_edgar/form_8k_lance/ \
      --recursive \
      --endpoint-url "$R2_ENDPOINT" \
      --no-cli-pager
  '\''
'

# s4 — ingest script: rollback is "git revert <merge-SHA>" (forward-only)
rollback_surface "s4" "hq-all" '
  echo "s4 rollback: git revert <merge-SHA> after merge (forward-only); see hotfix-revert PR flow in Stage 3.5"
'

# s3 — normalize: rollback is "git revert <merge-SHA>" (forward-only)
rollback_surface "s3" "hq-all" '
  echo "s3 rollback: git revert <merge-SHA> after merge (forward-only)"
'

# s2 — parser: rollback is "git revert <merge-SHA>" (forward-only)
rollback_surface "s2" "hq-all" '
  echo "s2 rollback: git revert <merge-SHA> after merge (forward-only)"
'

# s1 — migration: forward-only; rollback is "git revert <merge-SHA>" and the
# resulting empty up-migration on re-apply has no effect (IF NOT EXISTS).
# The table itself is preserved post-revert (Postgres state is forward-only too).
rollback_surface "s1" "hq-all" '
  echo "s1 rollback: git revert <merge-SHA> after merge (forward-only per apps/data-engine-x/supabase/migrations/README.md §Policy). Table ops.sec_edgar_form_8k_r2_ingest_runs is preserved; the revert removes the migration file from main."
'

echo "Rollback complete."
