#!/usr/bin/env bash
# Rollback harness for directive: sec-ria-targeting-mvs
# Generated by validator (skeleton). Audit subagent fills in concrete down-migration.
#
# Order (REVERSE of forward apply):
#   1. Unschedule both pg_cron jobs by jobname.
#   2. DROP MATERIALIZED VIEW IF EXISTS entities.mv_sec_signal_delta_adv_withdrawals.
#   3. DROP MATERIALIZED VIEW IF EXISTS entities.mv_sec_ria_firm_targeting.
#   4. (If smoke-query file merged) git revert that commit.
#
# Status at validator time: BLOCKED (see directive Validator notes).
# This rollback is a placeholder; do not execute until the audit subagent
# writes the paired down-migration AND the forward harness has run.
set -euo pipefail

echo "[rollback] sec-ria-targeting-mvs -- AUDIT MUST FILL THIS IN"
echo "[rollback] expected after audit:"
echo "  - doppler run --project data-engine-x --config prd -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -c \"SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname IN ('"'"'mv_sec_ria_firm_targeting_refresh'"'"', '"'"'mv_sec_signal_delta_adv_withdrawals_refresh'"'"');\"'"
echo "  - doppler run --project data-engine-x --config prd -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -c \"DROP MATERIALIZED VIEW IF EXISTS entities.mv_sec_signal_delta_adv_withdrawals;\"'"
echo "  - doppler run --project data-engine-x --config prd -- bash -c 'psql \"\$DEX_DB_URL_DIRECT\" -c \"DROP MATERIALIZED VIEW IF EXISTS entities.mv_sec_ria_firm_targeting;\"'"
exit 1
