#!/usr/bin/env bash
# Verify harness for /scope cycle sec-8k-item-203-extension.
#
# Runs all 7 surface verify commands. Exits 0 only if every check passes.
# Sourced via _lib-shim.sh from this same directory.
#
# Usage:
#   ./sec-8k-item-203-extension.sh                # run all surfaces
#   ./sec-8k-item-203-extension.sh --repo hq-all  # filter (no-op; single repo)
#
# Generated by Stage 3.A audit for directive
# ~/Desktop/hq/directives/2026-05-12-sec-8k-item-203-extension.md
set -euo pipefail

# shellcheck source=./_lib-shim.sh
source "$(dirname "$0")/_lib-shim.sh"

REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_FILTER="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

echo "==> Verifying surfaces for sec-8k-item-203-extension (filter: ${REPO_FILTER:-all})"

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

# s1 migration — table exists with the right CHECK constraint covering item_2_03
run_surface "s1" "hq-all" '
  dex_psql_query "SELECT 1 FROM pg_tables WHERE schemaname='\''ops'\'' AND tablename='\''sec_edgar_form_8k_r2_ingest_runs'\''" | grep -q 1 && \
  dex_psql_query "SELECT 1 FROM information_schema.check_constraints WHERE check_clause LIKE '\''%item_2_03_direct_financial_obligation%'\''" | grep -q 1
'

# s2 parser — file exists, importable, Item 2.03 in BODY_PARSE_ITEMS
run_surface "s2" "hq-all" '
  REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel) && \
  test -f "$REPO_ROOT/apps/data-engine-x/scripts/_lib/sec_edgar_form_8k_parser.py" && \
  grep -q "ITEM_2_03" "$REPO_ROOT/apps/data-engine-x/scripts/_lib/sec_edgar_form_8k_parser.py" && \
  grep -q "_parse_item_2_03" "$REPO_ROOT/apps/data-engine-x/scripts/_lib/sec_edgar_form_8k_parser.py"
'

# s3 normalize — file exists, classify_obligation_type defined
run_surface "s3" "hq-all" '
  REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel) && \
  test -f "$REPO_ROOT/apps/data-engine-x/scripts/_lib/sec_edgar_form_8k_normalize.py" && \
  grep -q "classify_obligation_type" "$REPO_ROOT/apps/data-engine-x/scripts/_lib/sec_edgar_form_8k_normalize.py"
'

# s4 ingest script — file exists, TARGET_RPS defaults to 1, item_2_03 stream wired
run_surface "s4" "hq-all" '
  REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel) && \
  test -f "$REPO_ROOT/apps/data-engine-x/scripts/run_sec_edgar_form_8k_r2_ingest.py" && \
  grep -qE "SEC_EDGAR_TARGET_RPS.*\"1\"" "$REPO_ROOT/apps/data-engine-x/scripts/run_sec_edgar_form_8k_r2_ingest.py" && \
  grep -q "item_2_03_direct_financial_obligation" "$REPO_ROOT/apps/data-engine-x/scripts/run_sec_edgar_form_8k_r2_ingest.py"
'

# s5 Lance emitter — file exists
run_surface "s5" "hq-all" '
  REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel) && \
  test -f "$REPO_ROOT/apps/data-engine-x/scripts/emit_sec_edgar_form_8k_lance.py"
'

# s6 ops.data_sources — both rows present + active
run_surface "s6" "hq-all" '
  dex_psql_query "SELECT 1 FROM ops.data_sources WHERE display_name='\''sec_edgar_form_8k'\'' AND status='\''active'\''" | grep -q 1 && \
  dex_psql_query "SELECT 1 FROM ops.data_sources WHERE display_name='\''sec_edgar_form_8k_lance'\'' AND status='\''active'\''" | grep -q 1
'

# s7 Modal cron — app file exists; (post-deploy) modal app list includes the app
run_surface "s7" "hq-all" '
  REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel) && \
  test -f "$REPO_ROOT/apps/data-engine-x/modal/sec_edgar_form_8k_app.py" && \
  grep -q "modal.Cron" "$REPO_ROOT/apps/data-engine-x/modal/sec_edgar_form_8k_app.py" && \
  grep -q "data-engine-x-sec-edgar-form-8k" "$REPO_ROOT/apps/data-engine-x/modal/sec_edgar_form_8k_app.py"
'

echo "All requested surfaces verified."
