#!/usr/bin/env bash
# Verification harness for directive: sec-ria-targeting-mvs
# Generated by validator (skeleton). Audit subagent fills in concrete verify SQL.
#
# Surfaces:
#   s1: migration -- both MVs exist + populated + cron job rows present.
#   s2: code     -- smoke query exits 0, returns non-zero counts.
#   s3: deploy   -- prod DB has the MVs and the cron schedule.
#
# Status at validator time: BLOCKED (see directive Validator notes).
# This harness is a placeholder; do not execute until the audit subagent
# fills in the verify commands AND the data blocker is resolved.
set -euo pipefail

REPO_FILTER="${1:-all}"

if [[ "$REPO_FILTER" != "all" && "$REPO_FILTER" != "data-engine-x" ]]; then
  echo "ERROR: only --repo data-engine-x is supported (single-repo migration)." >&2
  exit 2
fi

echo "[harness] sec-ria-targeting-mvs verify -- AUDIT MUST FILL THIS IN"
echo "[harness] expected after audit:"
echo "  - s1: psql checks both MVs are non-empty + cron.job rows for both"
echo "  - s2: psql -f apps/data-engine-x/scripts/sql/smoke_sec_ria_mvs.sql exits 0"
echo "  - s3: same as s1 against deployed prod DB (DEX_DB_URL_DIRECT)"
exit 1
