#!/usr/bin/env bash
# Rollback harness for directive: 2026-05-04-source-warn-notices-fl
# Generated by audit subagent.
#
# Reverses the migration in REVERSE order (s5 → s4 → s3 → s2 → s1).
#
# s5 (Modal app deploy + secret):
#   `modal app rollback data-engine-x-warn-notices-ingest` — first-class CLI
#   command (per `modal app rollback --help`) that redeploys the previous
#   version of the App from Modal's side. Falls back to `modal app stop` if
#   no prior version exists (first-ever deploy).
#   Modal secret deletion gated on SECRET_PRE_EXISTED env var:
#     SECRET_PRE_EXISTED=0 → newly created → `modal secret delete warn-notices-db`
#     SECRET_PRE_EXISTED=1 → pre-existing → no-op (don't touch operator's secret)
#     unset                → skip with warning (destructive default unsafe)
#
# s4 (migration apply to prod):
#   `git revert <merge-SHA>` removes the migration FILE; the post-merge hook
#   re-runs apply_pending_migrations.sh on the revert commit, which silently
#   no-ops (the file is gone). The TABLE persists because IF NOT EXISTS cannot
#   drop. To fully drop state (operator-confirmed only): the s1 step below runs
#   the DROP CASCADE explicitly via dex_psql_ddl.
#
# s3 + s2 (code):
#   Both files live on the merged commit. A single `git revert <merge-SHA>`
#   on bencrane/hq-all removes both. Pre-merge: don't merge.
#
# s1 (migration file revert + state cleanup):
#   File revert subsumed by s2 git revert. Optional state cleanup runs DROP
#   CASCADE — additive surface so safe; skip if you only want code-level revert.
#
# Forward-only repo policy per apps/data-engine-x/supabase/migrations/README.md
# §"Policy". No _down.sql.
#
# MERGE_SHA env var is required for s2/s3/s4 git revert. SECRET_PRE_EXISTED env
# var (0 or 1) controls s5 secret behavior.
#
# Usage:
#   MERGE_SHA=abc1234 SECRET_PRE_EXISTED=0 ./source-warn-notices-fl-rollback.sh
#   ./source-warn-notices-fl-rollback.sh --surface s1
#   ./source-warn-notices-fl-rollback.sh --repo data-engine-x

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface) SURFACE_FILTER="$2"; shift 2 ;;
    --repo)    REPO_FILTER="$2";    shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="${HQ_ALL:-/Users/benjamincrane/hq-all}"
APP_DIR="$HQ_ALL/apps/data-engine-x"

# Source the shim once at top — exposes dex_psql_ddl for s1 state-cleanup path.
# shellcheck source=/dev/null
source "$HOME/Desktop/hq-all/apps/data-engine-x/scripts/migration-checks/_lib-shim.sh"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

rollback_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then return 0; fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then return 0; fi
  echo "-- rollback $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- rollback $id ($repo): OK"
  else
    echo "-- rollback $id ($repo): FAILED" >&2
    return 1
  fi
}

echo "==> Rolling back source-warn-notices-fl surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all})"

# REVERSE order: s5 → s4 → s3 → s2 → s1.

# s5 — deploy: rollback the Modal app to its previous deployed version, or stop
# the app if this was the first-ever deploy. `modal app rollback` exits non-zero
# if there's no prior version; we fall back to `modal app stop` in that case.
# Then conditionally delete the Modal secret based on SECRET_PRE_EXISTED.
rollback_surface "s5" "data-engine-x" 'cd "$APP_DIR" && \
  if doppler run --project hq-all --config prd -- modal app rollback data-engine-x-warn-notices-ingest 2>&1 | tee /tmp/warn_notices_rollback_s5.log; then \
    echo "s5: rolled back to previous deployed version"; \
  else \
    echo "s5: rollback failed (likely first-ever deploy) — falling back to stop"; \
    doppler run --project hq-all --config prd -- modal app stop data-engine-x-warn-notices-ingest; \
  fi && \
  if [[ "${SECRET_PRE_EXISTED:-unset}" == "0" ]]; then \
    doppler run --project hq-all --config prd -- modal secret delete warn-notices-db; \
  elif [[ "${SECRET_PRE_EXISTED:-unset}" == "1" ]]; then \
    echo "s5 secret cleanup skipped: SECRET_PRE_EXISTED=1 (pre-existing — leaving operator-owned secret intact)"; \
    true; \
  else \
    echo "s5 secret cleanup skipped: SECRET_PRE_EXISTED unset — refusing to delete potentially-pre-existing secret. Set SECRET_PRE_EXISTED=0 or 1 explicitly to enable." >&2; \
    true; \
  fi'

# s4 — deploy: subsumed by s2 git revert below (the migration file goes away
# with the revert; the post-merge hook re-runs apply_pending_migrations.sh
# which is a no-op once the file is gone). State cleanup is in s1 below.
rollback_surface "s4" "data-engine-x" 'echo "s4 rollback subsumed by s2 git revert (post-merge hook re-runs apply_pending_migrations.sh which no-ops once migration file is gone). State cleanup runs in s1." && true'

# s3 — code: subsumed by s2's git revert below (single revert covers both files).
rollback_surface "s3" "data-engine-x" 'echo "s3 rollback subsumed by s2 git revert (same merge SHA covers both code files)" && true'

# s2 — code: open hotfix-revert PR on bencrane/hq-all and auto-merge it.
# Requires $MERGE_SHA to be set. Repo convention: hq-all auto-merges via repo
# workflow once CI is green; we use --auto so the merge happens automatically.
rollback_surface "s2" "data-engine-x" 'if [[ -z "${MERGE_SHA:-}" ]]; then echo "FAIL: MERGE_SHA env var must be set for s2/s3/s4 rollback" >&2; exit 2; fi && \
  cd "$HQ_ALL" && \
  git fetch origin main && \
  BR="hotfix/revert-source-warn-notices-fl-$(date -u +%Y%m%d-%H%M%S)" && \
  git checkout -b "$BR" origin/main && \
  git revert --no-edit "$MERGE_SHA" && \
  git push -u origin "$BR" && \
  gh -R bencrane/hq-all pr create --title "Revert: 2026-05-04-source-warn-notices-fl" --body "Auto-generated revert. Directive: /Users/benjamincrane/Desktop/hq/directives/2026-05-04-source-warn-notices-fl.md" --base main && \
  gh -R bencrane/hq-all pr merge --merge --auto --delete-branch'

# s1 — migration: file revert subsumed by s2 git revert; the table itself
# persists across the revert (additive shape, IF NOT EXISTS). For state
# cleanup if you want the tables gone (additive surface — safe DROP CASCADE):
rollback_surface "s1" "data-engine-x" 'echo "s1 file revert subsumed by s2 git revert (same MERGE_SHA covers migration). For state cleanup, dropping tables now (additive surface):" && \
  dex_psql_ddl "DROP TABLE IF EXISTS entities.source_warn_notices CASCADE; DROP TABLE IF EXISTS ops.warn_notices_ingest_runs CASCADE;"'

echo "==> Rollback complete."
