#!/usr/bin/env bash
# Verification harness for directive: 2026-05-04-source-warn-notices-fl
# Generated by audit subagent.
#
# Surfaces (5, single repo bencrane/hq-all → apps/data-engine-x):
#   s1  migration  apps/data-engine-x/supabase/migrations/{ts}_create_source_warn_notices.sql
#                  → entities.source_warn_notices       (PK state, source_notice_id)
#                  → ops.warn_notices_ingest_runs       (run-grain audit table)
#                  Source table: 1:1 mirror of FL HTML cols + raw_source_row jsonb NOT NULL
#                  + full 9-col canonical provenance set.
#   s2  code       apps/data-engine-x/scripts/run_warn_notices_ingest.py
#                  → static checks (file tracked + parses + has expected shape)
#   s3  code       apps/data-engine-x/modal/warn_notices_ingest_app.py
#                  → static checks (file tracked + parses + app-name/cron/secret)
#   s4  deploy     migration applied to prod (post-merge hook)
#                  → entities.source_warn_notices exists with full provenance
#                  → ops.warn_notices_ingest_runs exists
#   s5  deploy     Modal app `data-engine-x-warn-notices-ingest` deployed
#                  → modal secret `warn-notices-db` exists
#                  → modal app list shows app deployed
#                  → ops.warn_notices_ingest_runs latest row succeeded (post-first-ingest)
#                  → dex_min_row_floor_check entities.source_warn_notices 500
#                    (skip with --skip-volume-floor on first-deploy pass before any ingest)
#
# Doppler idiom (per apps/data-engine-x/CLAUDE.md §"Doppler shell gotcha"):
#   doppler run -- bash -c 'psql "$DEX_DB_URL_DIRECT" -c "..."'
# Doppler project/config pinned per-directory via apps/data-engine-x/doppler.yaml;
# helper library defaults to project=hq-all config=prd (FAA precedent).
#
# Helper functions (dex_provenance_check, dex_min_row_floor_check, dex_psql_query)
# come from apps/data-engine-x/scripts/_lib/dex.sh — sourced via the vault thin shim.
#
# Usage:
#   ./source-warn-notices-fl.sh
#   ./source-warn-notices-fl.sh --surface s1
#   ./source-warn-notices-fl.sh --repo data-engine-x
#   ./source-warn-notices-fl.sh --skip-volume-floor      # first-deploy pass
#
# Exits 0 only if every requested surface passes.

set -euo pipefail

SURFACE_FILTER=""
REPO_FILTER=""
SKIP_VOLUME_FLOOR=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --surface)            SURFACE_FILTER="$2"; shift 2 ;;
    --repo)               REPO_FILTER="$2";    shift 2 ;;
    --skip-volume-floor)  SKIP_VOLUME_FLOOR=1; shift ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

HQ_ALL="${HQ_ALL:-/Users/benjamincrane/hq-all}"
APP_DIR="$HQ_ALL/apps/data-engine-x"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source the shim once at top — exposes dex_psql_query, dex_psql_ddl,
# dex_provenance_check, dex_min_row_floor_check, dex_idempotency_check.
# shellcheck source=/dev/null
source "$HOME/Desktop/hq-all/apps/data-engine-x/scripts/migration-checks/_lib-shim.sh"

if [[ ! -d "$APP_DIR" ]]; then
  echo "FAIL: app dir missing: $APP_DIR" >&2
  exit 1
fi

# Sidecar SQL file (FAA / Overture precedent).
S1_SQL_FILE="$SCRIPT_DIR/source-warn-notices-fl-s1-verify.sql"
if [[ ! -f "$S1_SQL_FILE" ]]; then
  echo "FAIL: sidecar SQL missing: $S1_SQL_FILE" >&2
  exit 1
fi

# Confirm hq-all has bencrane/hq-all as origin remote (not a fork or stale clone).
REMOTE=$(git -C "$HQ_ALL" remote get-url origin 2>&1 || echo "MISSING")
if [[ "$REMOTE" != *"bencrane/hq-all"* ]]; then
  echo "FAIL: $HQ_ALL origin is '$REMOTE' — expected bencrane/hq-all" >&2
  exit 1
fi

run_surface() {
  local id="$1" repo="$2" cmd="$3"
  if [[ -n "$SURFACE_FILTER" && "$SURFACE_FILTER" != "$id" ]]; then
    echo "-- $id ($repo): SKIPPED (surface filter)"
    return 0
  fi
  if [[ -n "$REPO_FILTER" && "$REPO_FILTER" != "$repo" ]]; then
    echo "-- $id ($repo): SKIPPED (repo filter)"
    return 0
  fi
  echo "-- $id ($repo): RUNNING"
  if eval "$cmd"; then
    echo "-- $id ($repo): PASS"
  else
    echo "-- $id ($repo): FAIL" >&2
    return 1
  fi
}

echo "==> Verifying source-warn-notices-fl surfaces (surface: ${SURFACE_FILTER:-all}, repo: ${REPO_FILTER:-all}, skip-volume-floor: $SKIP_VOLUME_FLOOR)"

# s1 — migration: source + ops tables exist (sidecar SQL),
# AND the source table has the canonical 9-column provenance set.
run_surface "s1" "data-engine-x" 'dex_psql_query "$(cat '"$S1_SQL_FILE"')" | grep -q "^1$" && \
  dex_provenance_check entities.source_warn_notices'

# s2 — code: ingest script tracked, parses, references expected table names,
# env var, ON CONFLICT, raw_source_row, FL portal URL host, and provider literal.
run_surface "s2" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/scripts/run_warn_notices_ingest.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/scripts/run_warn_notices_ingest.py\").read())" && \
  grep -q "entities.source_warn_notices" apps/data-engine-x/scripts/run_warn_notices_ingest.py && \
  grep -q "ops.warn_notices_ingest_runs" apps/data-engine-x/scripts/run_warn_notices_ingest.py && \
  grep -q "DEX_DB_URL_POOLED" apps/data-engine-x/scripts/run_warn_notices_ingest.py && \
  grep -q "ON CONFLICT" apps/data-engine-x/scripts/run_warn_notices_ingest.py && \
  grep -q "raw_source_row" apps/data-engine-x/scripts/run_warn_notices_ingest.py && \
  grep -q "reactwarn.floridajobs.org" apps/data-engine-x/scripts/run_warn_notices_ingest.py && \
  grep -q "fl_warn_notices" apps/data-engine-x/scripts/run_warn_notices_ingest.py && \
  grep -q "sha256" apps/data-engine-x/scripts/run_warn_notices_ingest.py'

# s3 — code: Modal wrapper tracked, parses, declares the expected app name,
# weekly Sunday-midnight cron, and named secret.
run_surface "s3" "data-engine-x" 'cd "$HQ_ALL" && \
  git ls-files --error-unmatch apps/data-engine-x/modal/warn_notices_ingest_app.py >/dev/null 2>&1 && \
  python3 -c "import ast; ast.parse(open(\"apps/data-engine-x/modal/warn_notices_ingest_app.py\").read())" && \
  grep -q "data-engine-x-warn-notices-ingest" apps/data-engine-x/modal/warn_notices_ingest_app.py && \
  grep -q "modal.Cron(\"0 0 \* \* 0\")" apps/data-engine-x/modal/warn_notices_ingest_app.py && \
  grep -q "from_name(\"warn-notices-db\")" apps/data-engine-x/modal/warn_notices_ingest_app.py'

# s4 — deploy: migration applied to prod. Same SQL/provenance shape as s1
# but evaluated post-merge against prod DB (the post-merge hook fires
# apply_pending_migrations.sh automatically). Volume floor is checked in s5.
run_surface "s4" "data-engine-x" 'dex_psql_query "$(cat '"$S1_SQL_FILE"')" | grep -q "^1$" && \
  dex_provenance_check entities.source_warn_notices'

# s5 — deploy: Modal secret + app deployed + latest run succeeded + volume floor.
# The (.Name // .name) and (.Description // .name) fallbacks handle Modal CLI 1.4.x
# TitleCase keys (FAA / Overture precedent).
# Volume floor (500) is conditional: skip on first-deploy pass via --skip-volume-floor
# until at least one ingest completes (full backfill = 2,565 rows; first-cron will
# populate). Also gates the latest-run-succeeded check on at least one ingest existing.
if [[ $SKIP_VOLUME_FLOOR -eq 1 ]]; then
  run_surface "s5" "data-engine-x" 'modal secret list --json | jq -e '"'"'.[] | select((.Name // .name) == "warn-notices-db")'"'"' >/dev/null && \
    modal app list --json | jq -e '"'"'.[] | select(((.["Description"] // .name) == "data-engine-x-warn-notices-ingest") and (((.["State"] // .state) | ascii_downcase) == "deployed"))'"'"' >/dev/null'
else
  run_surface "s5" "data-engine-x" 'modal secret list --json | jq -e '"'"'.[] | select((.Name // .name) == "warn-notices-db")'"'"' >/dev/null && \
    modal app list --json | jq -e '"'"'.[] | select(((.["Description"] // .name) == "data-engine-x-warn-notices-ingest") and (((.["State"] // .state) | ascii_downcase) == "deployed"))'"'"' >/dev/null && \
    [[ "$(dex_psql_query "SELECT status FROM ops.warn_notices_ingest_runs ORDER BY started_at DESC LIMIT 1")" == "succeeded" ]] && \
    dex_min_row_floor_check entities.source_warn_notices 500'
fi

echo "==> All requested surfaces verified."
