from __future__ import annotations

from dataclasses import dataclass
from datetime import time
from typing import Literal

SourceKind = Literal["daily_diff_txt", "snapshot_txt", "sms_csv", "csv_export"]
SizeClass = Literal["small", "medium", "large"]
# Worker-pool selection. "normal" → ingest_one_feed (90-min Modal timeout).
# "xl" → ingest_one_feed_xl (6-hour timeout). Sized off observed 30-day p95
# of completed_at - started_at: any feed whose p95 ever exceeded ~80 min, or
# whose worker has been observed timing out (Modal SIGKILL at 5400s), is
# tagged "xl". This is independent of size_class (which is about file bytes,
# not wall-clock).
WorkerSize = Literal["normal", "xl"]


@dataclass(frozen=True)
class FeedConfig:
    feed_name: str
    source_kind: SourceKind
    source_file_variant: str
    download_url: str
    table_name: str
    source_fields: tuple[str, ...]
    expected_field_count: int
    header_row: tuple[str, ...] | None
    schedule_time_et: time
    chunk_size: int
    size_class: SizeClass
    worker_size: WorkerSize = "normal"


def _build_schedule_times() -> list[time]:
    """Generate the legacy 7-minute stagger from 10:05 to 13:35 ET."""
    times: list[time] = []
    hour = 10
    minute = 5
    for _ in range(31):
        times.append(time(hour=hour, minute=minute))
        minute += 7
        if minute >= 60:
            hour += minute // 60
            minute = minute % 60
    return times


SCHEDULE_TIMES_ET = _build_schedule_times()


FMCSA_AUTHHIST_SOURCE_FIELDS = (
    "Docket Number",
    "USDOT Number",
    "Sub Number",
    "Operating Authority Type",
    "Original Authority Action Description",
    "Original Authority Action Served Date",
    "Final Authority Action Description",
    "Final Authority Decision Date",
    "Final Authority Served Date",
)

FMCSA_REVOCATION_SOURCE_FIELDS = (
    "Docket Number",
    "USDOT Number",
    "Operating Authority Registration Type",
    "Serve Date",
    "Revocation Type",
    "Effective Date",
)

FMCSA_INSURANCE_SOURCE_FIELDS = (
    "Docket Number",
    "Insurance Type",
    "BI&PD Class",
    "BI&PD Maximum Dollar Limit",
    "BI&PD Underlying Dollar Limit",
    "Policy Number",
    "Effective Date",
    "Form Code",
    "Insurance Company Name",
)

FMCSA_ACTPENDINSUR_SOURCE_FIELDS = (
    "Docket Number",
    "USDOT Number",
    "Form Code",
    "Insurance Type Description",
    "Insurance Company Name",
    "Policy Number",
    "Posted Date",
    "BI&PD Underlying Limit",
    "BI&PD Maximum Limit",
    "Effective Date",
    "Cancel Effective Date",
)

FMCSA_INSHIST_SOURCE_FIELDS = (
    "Docket Number",
    "USDOT Number",
    "Form Code",
    "Cancellation Method",
    "Cancel/Replace/Name Change/Transfer Form",
    "Insurance Type Indicator",
    "Insurance Type Description",
    "Policy Number",
    "Minimum Coverage Amount",
    "Insurance Class Code",
    "Effective Date",
    "BI&PD Underlying Limit Amount",
    "BI&PD Max Coverage Amount",
    "Cancel Effective Date",
    "Specific Cancellation Method",
    "Insurance Company Branch",
    "Insurance Company Name",
)

FMCSA_CARRIER_SOURCE_FIELDS = (
    "Docket Number",
    "USDOT Number",
    "MX Type",
    "RFC Number",
    "Common Authority",
    "Contract Authority",
    "Broker Authority",
    "Pending Common Authority",
    "Pending Contract Authority",
    "Pending Broker Authority",
    "Common Authority Revocation",
    "Contract Authority Revocation",
    "Broker Authority Revocation",
    "Property",
    "Passenger",
    "Household Goods",
    "Private Check",
    "Enterprise Check",
    "BIPD Required",
    "Cargo Required",
    "Bond/Surety Required",
    "BIPD on File",
    "Cargo on File",
    "Bond/Surety on File",
    "Address Status",
    "DBA Name",
    "Legal Name",
    "Business Address - PO Box/Street",
    "Business Address - Colonia",
    "Business Address - City",
    "Business Address - State Code",
    "Business Address - Country Code",
    "Business Address - Zip Code",
    "Business Address - Telephone Number",
    "Business Address - Fax Number",
    "Mailing Address - PO Box/Street",
    "Mailing Address - Colonia",
    "Mailing Address - City",
    "Mailing Address - State Code",
    "Mailing Address - Country Code",
    "Mailing Address - Zip Code",
    "Mailing Address - Telephone Number",
    "Mailing Address - Fax Number",
)

FMCSA_REJECTED_SOURCE_FIELDS = (
    "Docket Number",
    "USDOT Number",
    "Form Code (Insurance or Cancel)",
    "Insurance Type Description",
    "Policy Number",
    "Received Date",
    "Insurance Class Code",
    "Insurance Type Code",
    "Underlying Limit Amount",
    "Maximum Coverage Amount",
    "Rejected Date",
    "Insurance Branch",
    "Company Name",
    "Rejected Reason",
    "Minimum Coverage Amount",
)

FMCSA_BOC3_SOURCE_FIELDS = (
    "Docket Number",
    "USDOT Number",
    "Company Name",
    "Attention to or Title",
    "Street or PO Box",
    "City",
    "State",
    "Country",
    "Zip Code",
)

FMCSA_CRASH_FILE_SOURCE_FIELDS = (
    "CHANGE_DATE",
    "CRASH_ID",
    "REPORT_STATE",
    "REPORT_NUMBER",
    "REPORT_DATE",
    "REPORT_TIME",
    "REPORT_SEQ_NO",
    "DOT_NUMBER",
    "CI_STATUS_CODE",
    "FINAL_STATUS_DATE",
    "LOCATION",
    "CITY_CODE",
    "CITY",
    "STATE",
    "COUNTY_CODE",
    "TRUCK_BUS_IND",
    "TRAFFICWAY_ID",
    "ACCESS_CONTROL_ID",
    "ROAD_SURFACE_CONDITION_ID",
    "CARGO_BODY_TYPE_ID",
    "GVW_RATING_ID",
    "VEHICLE_IDENTIFICATION_NUMBER",
    "VEHICLE_LICENSE_NUMBER",
    "VEHICLE_LIC_STATE",
    "VEHICLE_HAZMAT_PLACARD",
    "WEATHER_CONDITION_ID",
    "VEHICLE_CONFIGURATION_ID",
    "LIGHT_CONDITION_ID",
    "HAZMAT_RELEASED",
    "AGENCY",
    "VEHICLES_IN_ACCIDENT",
    "FATALITIES",
    "INJURIES",
    "TOW_AWAY",
    "FEDERAL_RECORDABLE",
    "STATE_RECORDABLE",
    "SNET_VERSION_NUMBER",
    "SNET_SEQUENCE_ID",
    "TRANSACTION_CODE",
    "TRANSACTION_DATE",
    "UPLOAD_FIRST_BYTE",
    "UPLOAD_DOT_NUMBER",
    "UPLOAD_SEARCH_INDICATOR",
    "UPLOAD_DATE",
    "ADD_DATE",
    "CRASH_CARRIER_ID",
    "CRASH_CARRIER_NAME",
    "CRASH_CARRIER_STREET",
    "CRASH_CARRIER_CITY",
    "CRASH_CARRIER_CITY_CODE",
    "CRASH_CARRIER_STATE",
    "CRASH_CARRIER_ZIP_CODE",
    "CRASH_COLONIA",
    "DOCKET_NUMBER",
    "CRASH_CARRIER_INTERSTATE",
    "NO_ID_FLAG",
    "STATE_NUMBER",
    "STATE_ISSUING_NUMBER",
    "CRASH_EVENT_SEQ_ID_DESC",
)

FMCSA_CARRIER_ALL_HISTORY_HEADERS = (
    "DOCKET_NUMBER",
    "DOT_NUMBER",
    "MX_TYPE",
    "RFC_NUMBER",
    "COMMON_STAT",
    "CONTRACT_STAT",
    "BROKER_STAT",
    "COMMON_APP_PEND",
    "CONTRACT_APP_PEND",
    "BROKER_APP_PEND",
    "COMMON_REV_PEND",
    "CONTRACT_REV_PEND",
    "BROKER_REV_PEND",
    "PROPERTY_CHK",
    "PASSENGER_CHK",
    "HHG_CHK",
    "PRIVATE_AUTH_CHK",
    "ENTERPRISE_CHK",
    "MIN_COV_AMOUNT",
    "CARGO_REQ",
    "BOND_REQ",
    "BIPD_FILE",
    "CARGO_FILE",
    "BOND_FILE",
    "UNDELIVERABLE_MAIL",
    "DBA_NAME",
    "LEGAL_NAME",
    "BUS_STREET_PO",
    "BUS_COLONIA",
    "BUS_CITY",
    "BUS_STATE_CODE",
    "BUS_CTRY_CODE",
    "BUS_ZIP_CODE",
    "BUS_TELNO",
    "BUS_FAX",
    "MAIL_STREET_PO",
    "MAIL_COLONIA",
    "MAIL_CITY",
    "MAIL_STATE_CODE",
    "MAIL_CTRY_CODE",
    "MAIL_ZIP_CODE",
    "MAIL_TELNO",
    "MAIL_FAX",
)

FMCSA_INSPECTION_UNITS_SOURCE_FIELDS = (
    "CHANGE_DATE",
    "INSPECTION_ID",
    "INSP_UNIT_ID",
    "INSP_UNIT_TYPE_ID",
    "INSP_UNIT_NUMBER",
    "INSP_UNIT_MAKE",
    "INSP_UNIT_COMPANY",
    "INSP_UNIT_LICENSE",
    "INSP_UNIT_LICENSE_STATE",
    "INSP_UNIT_VEHICLE_ID_NUMBER",
    "INSP_UNIT_DECAL",
    "INSP_UNIT_DECAL_NUMBER",
)

FMCSA_SPECIAL_STUDIES_SOURCE_FIELDS = (
    "CHANGE_DATE",
    "INSPECTION_ID",
    "INSP_STUDY_ID",
    "STUDY",
    "SEQ_NO",
)

FMCSA_REVOCATION_ALL_HISTORY_HEADERS = (
    "DOCKET_NUMBER",
    "DOT_NUMBER",
    "TYPE_LICENSE",
    "ORDER1_SERVE_DATE",
    "ORDER2_TYPE_DESC",
    "order2_effective_Date",
)

FMCSA_INSUR_ALL_HISTORY_HEADERS = (
    "prefix_docket_number",
    "ins_type_code",
    "ins_class_code",
    "max_cov_amount",
    "underl_lim_amount",
    "policy_no",
    "effective_date",
    "ins_form_code",
    "name_company",
)

FMCSA_OUT_OF_SERVICE_ORDER_SOURCE_FIELDS = (
    "DOT_NUMBER",
    "LEGAL_NAME",
    "DBA_NAME",
    "OOS_DATE",
    "OOS_REASON",
    "STATUS",
    "OOS_RESCIND_DATE",
)

FMCSA_OUT_OF_SERVICE_ORDER_HEADERS = (
    "DOT_NUMBER",
    "LEGAL_NAME",
    "DBA_NAME",
    "OOS_DATE",
    "OOS_REASON",
    "STATUS",
    "RESCIND_DATE",
)

FMCSA_INSPECTION_CITATIONS_SOURCE_FIELDS = (
    "CHANGE_DATE",
    "INSPECTION_ID",
    "VIOSEQNUM",
    "ADJSEQ",
    "CITATION_CODE",
    "CITATION_RESULT",
)

FMCSA_VEHICLE_INSPECTION_VIOLATIONS_SOURCE_FIELDS = (
    "CHANGE_DATE",
    "INSPECTION_ID",
    "INSP_VIOLATION_ID",
    "SEQ_NO",
    "PART_NO",
    "PART_NO_SECTION",
    "INSP_VIOL_UNIT",
    "INSP_UNIT_ID",
    "INSP_VIOLATION_CATEGORY_ID",
    "OUT_OF_SERVICE_INDICATOR",
    "DEFECT_VERIFICATION_ID",
    "CITATION_NUMBER",
)

FMCSA_COMPANY_CENSUS_SOURCE_FIELDS = (
    "MCS150_DATE",
    "ADD_DATE",
    "STATUS_CODE",
    "DOT_NUMBER",
    "DUN_BRADSTREET_NO",
    "PHY_OMC_REGION",
    "SAFETY_INV_TERR",
    "CARRIER_OPERATION",
    "BUSINESS_ORG_ID",
    "MCS150_MILEAGE",
    "MCS150_MILEAGE_YEAR",
    "MCS151_MILEAGE",
    "TOTAL_CARS",
    "MCS150_UPDATE_CODE_ID",
    "PRIOR_REVOKE_FLAG",
    "PRIOR_REVOKE_DOT_NUMBER",
    "PHONE",
    "FAX",
    "CELL_PHONE",
    "COMPANY_OFFICER_1",
    "COMPANY_OFFICER_2",
    "BUSINESS_ORG_DESC",
    "TRUCK_UNITS",
    "POWER_UNITS",
    "BUS_UNITS",
    "FLEETSIZE",
    "REVIEW_ID",
    "RECORDABLE_CRASH_RATE",
    "MAIL_NATIONALITY_INDICATOR",
    "PHY_NATIONALITY_INDICATOR",
    "PHY_BARRIO",
    "MAIL_BARRIO",
    "CARSHIP",
    "DOCKET1PREFIX",
    "DOCKET1",
    "DOCKET2PREFIX",
    "DOCKET2",
    "DOCKET3PREFIX",
    "DOCKET3",
    "POINTNUM",
    "TOTAL_INTRASTATE_DRIVERS",
    "MCSIPSTEP",
    "MCSIPDATE",
    "HM_Ind",
    "INTERSTATE_BEYOND_100_MILES",
    "INTERSTATE_WITHIN_100_MILES",
    "INTRASTATE_BEYOND_100_MILES",
    "INTRASTATE_WITHIN_100_MILES",
    "TOTAL_CDL",
    "TOTAL_DRIVERS",
    "AVG_DRIVERS_LEASED_PER_MONTH",
    "CLASSDEF",
    "LEGAL_NAME",
    "DBA_NAME",
    "PHY_STREET",
    "PHY_CITY",
    "PHY_COUNTRY",
    "PHY_STATE",
    "PHY_ZIP",
    "PHY_CNTY",
    "CARRIER_MAILING_STREET",
    "CARRIER_MAILING_STATE",
    "CARRIER_MAILING_CITY",
    "CARRIER_MAILING_COUNTRY",
    "CARRIER_MAILING_ZIP",
    "CARRIER_MAILING_CNTY",
    "CARRIER_MAILING_UND_DATE",
    "DRIVER_INTER_TOTAL",
    "EMAIL_ADDRESS",
    "REVIEW_TYPE",
    "REVIEW_DATE",
    "SAFETY_RATING",
    "SAFETY_RATING_DATE",
    "UNDELIV_PHY",
    "CRGO_GENFREIGHT",
    "CRGO_HOUSEHOLD",
    "CRGO_METALSHEET",
    "CRGO_MOTOVEH",
    "CRGO_DRIVETOW",
    "CRGO_LOGPOLE",
    "CRGO_BLDGMAT",
    "CRGO_MOBILEHOME",
    "CRGO_MACHLRG",
    "CRGO_PRODUCE",
    "CRGO_LIQGAS",
    "CRGO_INTERMODAL",
    "CRGO_PASSENGERS",
    "CRGO_OILFIELD",
    "CRGO_LIVESTOCK",
    "CRGO_GRAINFEED",
    "CRGO_COALCOKE",
    "CRGO_MEAT",
    "CRGO_GARBAGE",
    "CRGO_USMAIL",
    "CRGO_CHEM",
    "CRGO_DRYBULK",
    "CRGO_COLDFOOD",
    "CRGO_BEVERAGES",
    "CRGO_PAPERPROD",
    "CRGO_UTILITY",
    "CRGO_FARMSUPP",
    "CRGO_CONSTRUCT",
    "CRGO_WATERWELL",
    "CRGO_CARGOOTHR",
    "CRGO_CARGOOTHR_DESC",
    "OWNTRUCK",
    "OWNTRACT",
    "OWNTRAIL",
    "OWNCOACH",
    "OWNSCHOOL_1_8",
    "OWNSCHOOL_9_15",
    "OWNSCHOOL_16",
    "OWNBUS_16",
    "OWNVAN_1_8",
    "OWNVAN_9_15",
    "OWNLIMO_1_8",
    "OWNLIMO_9_15",
    "OWNLIMO_16",
    "TRMTRUCK",
    "TRMTRACT",
    "TRMTRAIL",
    "TRMCOACH",
    "TRMSCHOOL_1_8",
    "TRMSCHOOL_9_15",
    "TRMSCHOOL_16",
    "TRMBUS_16",
    "TRMVAN_1_8",
    "TRMVAN_9_15",
    "TRMLIMO_1_8",
    "TRMLIMO_9_15",
    "TRMLIMO_16",
    "TRPTRUCK",
    "TRPTRACT",
    "TRPTRAIL",
    "TRPCOACH",
    "TRPSCHOOL_1_8",
    "TRPSCHOOL_9_15",
    "TRPSCHOOL_16",
    "TRPBUS_16",
    "TRPVAN_1_8",
    "TRPVAN_9_15",
    "TRPLIMO_1_8",
    "TRPLIMO_9_15",
    "TRPLIMO_16",
    "DOCKET1_STATUS_CODE",
    "DOCKET2_STATUS_CODE",
    "DOCKET3_STATUS_CODE",
)

FMCSA_VEHICLE_INSPECTION_FILE_SOURCE_FIELDS = (
    "CHANGE_DATE",
    "INSPECTION_ID",
    "DOT_NUMBER",
    "REPORT_STATE",
    "REPORT_NUMBER",
    "INSP_DATE",
    "INSP_START_TIME",
    "INSP_END_TIME",
    "REGISTRATION_DATE",
    "REGION",
    "CI_STATUS_CODE",
    "LOCATION",
    "LOCATION_DESC",
    "COUNTY_CODE_STATE",
    "COUNTY_CODE",
    "INSP_LEVEL_ID",
    "SERVICE_CENTER",
    "CENSUS_SOURCE_ID",
    "INSP_FACILITY",
    "SHIPPER_NAME",
    "SHIPPING_PAPER_NUMBER",
    "CARGO_TANK",
    "HAZMAT_PLACARD_REQ",
    "SNET_VERSION_NUMBER",
    "SNET_SEARCH_DATE",
    "ALCOHOL_CONTROL_SUB",
    "DRUG_INTRDCTN_SEARCH",
    "DRUG_INTRDCTN_ARRESTS",
    "SIZE_WEIGHT_ENF",
    "TRAFFIC_ENF",
    "LOCAL_ENF_JURISDICTION",
    "PEN_CEN_MATCH",
    "FINAL_STATUS_DATE",
    "POST_ACC_IND",
    "GROSS_COMB_VEH_WT",
    "VIOL_TOTAL",
    "OOS_TOTAL",
    "DRIVER_VIOL_TOTAL",
    "DRIVER_OOS_TOTAL",
    "VEHICLE_VIOL_TOTAL",
    "VEHICLE_OOS_TOTAL",
    "HAZMAT_VIOL_TOTAL",
    "HAZMAT_OOS_TOTAL",
    "SNET_SEQUENCE_ID",
    "TRANSACTION_CODE",
    "TRANSACTION_DATE",
    "UPLOAD_DATE",
    "UPLOAD_FIRST_BYTE",
    "UPLOAD_DOT_NUMBER",
    "UPLOAD_SEARCH_INDICATOR",
    "CENSUS_SEARCH_DATE",
    "SNET_INPUT_DATE",
    "SOURCE_OFFICE",
    "MCMIS_ADD_DATE",
    "INSP_CARRIER_NAME",
    "INSP_CARRIER_STREET",
    "INSP_CARRIER_CITY",
    "INSP_CARRIER_STATE",
    "INSP_CARRIER_ZIP_CODE",
    "INSP_COLONIA",
    "DOCKET_NUMBER",
    "INSP_INTERSTATE",
    "INSP_CARRIER_STATE_ID",
)

SMS_PASSPROPERTY_SOURCE_FIELDS = (
    "DOT_NUMBER",
    "INSP_TOTAL",
    "DRIVER_INSP_TOTAL",
    "DRIVER_OOS_INSP_TOTAL",
    "VEHICLE_INSP_TOTAL",
    "VEHICLE_OOS_INSP_TOTAL",
    "UNSAFE_DRIV_INSP_W_VIOL",
    "UNSAFE_DRIV_MEASURE",
    "UNSAFE_DRIV_AC",
    "HOS_DRIV_INSP_W_VIOL",
    "HOS_DRIV_MEASURE",
    "HOS_DRIV_AC",
    "DRIV_FIT_INSP_W_VIOL",
    "DRIV_FIT_MEASURE",
    "DRIV_FIT_AC",
    "CONTR_SUBST_INSP_W_VIOL",
    "CONTR_SUBST_MEASURE",
    "CONTR_SUBST_AC",
    "VEH_MAINT_INSP_W_VIOL",
    "VEH_MAINT_MEASURE",
    "VEH_MAINT_AC",
)

SMS_PASS_SOURCE_FIELDS = (
    "DOT_NUMBER",
    "INSP_TOTAL",
    "DRIVER_INSP_TOTAL",
    "DRIVER_OOS_INSP_TOTAL",
    "VEHICLE_INSP_TOTAL",
    "VEHICLE_OOS_INSP_TOTAL",
    "UNSAFE_DRIV_INSP_W_VIOL",
    "UNSAFE_DRIV_MEASURE",
    "UNSAFE_DRIV_PCT",
    "UNSAFE_DRIV_RD_ALERT",
    "UNSAFE_DRIV_AC",
    "UNSAFE_DRIV_BASIC_ALERT",
    "HOS_DRIV_INSP_W_VIOL",
    "HOS_DRIV_MEASURE",
    "HOS_DRIV_PCT",
    "HOS_DRIV_RD_ALERT",
    "HOS_DRIV_AC",
    "HOS_DRIV_BASIC_ALERT",
    "DRIV_FIT_INSP_W_VIOL",
    "DRIV_FIT_MEASURE",
    "DRIV_FIT_PCT",
    "DRIV_FIT_RD_ALERT",
    "DRIV_FIT_AC",
    "DRIV_FIT_BASIC_ALERT",
    "CONTR_SUBST_INSP_W_VIOL",
    "CONTR_SUBST_MEASURE",
    "CONTR_SUBST_PCT",
    "CONTR_SUBST_RD_ALERT",
    "CONTR_SUBST_AC",
    "CONTR_SUBST_BASIC_ALERT",
    "VEH_MAINT_INSP_W_VIOL",
    "VEH_MAINT_MEASURE",
    "VEH_MAINT_PCT",
    "VEH_MAINT_RD_ALERT",
    "VEH_MAINT_AC",
    "VEH_MAINT_BASIC_ALERT",
)

SMS_INPUT_VIOLATION_SOURCE_FIELDS = (
    "Unique_ID",
    "Insp_Date",
    "DOT_Number",
    "Viol_Code",
    "BASIC_Desc",
    "OOS_Indicator",
    "OOS_Weight",
    "Severity_Weight",
    "Time_Weight",
    "Total_Severity_Wght",
    "Section_Desc",
    "Group_Desc",
    "Viol_Unit",
)

SMS_INPUT_INSPECTION_SOURCE_FIELDS = (
    "Unique_ID",
    "Report_Number",
    "Report_State",
    "DOT_Number",
    "Insp_Date",
    "Insp_level_ID",
    "County_code_State",
    "Time_Weight",
    "Driver_OOS_Total",
    "Vehicle_OOS_Total",
    "Total_Hazmat_Sent",
    "OOS_Total",
    "Hazmat_OOS_Total",
    "Hazmat_Placard_req",
    "Unit_Type_Desc",
    "Unit_Make",
    "Unit_License",
    "Unit_License_State",
    "VIN",
    "Unit_Decal_Number",
    "Unit_Type_Desc2",
    "Unit_Make2",
    "Unit_License2",
    "Unit_License_State2",
    "VIN2",
    "Unit_Decal_Number2",
    "Unsafe_Insp",
    "Fatigued_Insp",
    "Dr_Fitness_Insp",
    "Subt_Alcohol_Insp",
    "Vh_Maint_Insp",
    "HM_Insp",
    "BASIC_Viol",
    "Unsafe_Viol",
    "Fatigued_Viol",
    "Dr_Fitness_Viol",
    "Subt_Alcohol_Viol",
    "Vh_Maint_Viol",
    "HM_Viol",
)

SMS_MOTOR_CARRIER_CENSUS_SOURCE_FIELDS = (
    "DOT_NUMBER",
    "LEGAL_NAME",
    "DBA_NAME",
    "CARRIER_OPERATION",
    "HM_FLAG",
    "PC_FLAG",
    "PHY_STREET",
    "PHY_CITY",
    "PHY_STATE",
    "PHY_ZIP",
    "PHY_COUNTRY",
    "MAILING_STREET",
    "MAILING_CITY",
    "MAILING_STATE",
    "MAILING_ZIP",
    "MAILING_COUNTRY",
    "TELEPHONE",
    "FAX",
    "EMAIL_ADDRESS",
    "MCS150_DATE",
    "MCS150_MILEAGE",
    "MCS150_MILEAGE_YEAR",
    "ADD_DATE",
    "OIC_STATE",
    "NBR_POWER_UNIT",
    "DRIVER_TOTAL",
    "RECENT_MILEAGE",
    "RECENT_MILEAGE_YEAR",
    "VMT_SOURCE_ID",
    "PRIVATE_ONLY",
    "AUTHORIZED_FOR_HIRE",
    "EXEMPT_FOR_HIRE",
    "PRIVATE_PROPERTY",
    "PRIVATE_PASSENGER_BUSINESS",
    "PRIVATE_PASSENGER_NONBUSINESS",
    "MIGRANT",
    "US_MAIL",
    "FEDERAL_GOVERNMENT",
    "STATE_GOVERNMENT",
    "LOCAL_GOVERNMENT",
    "INDIAN_TRIBE",
    "OP_OTHER",
)


def _feed(
    *,
    feed_name: str,
    source_kind: SourceKind,
    source_file_variant: str,
    download_url: str,
    table_name: str,
    source_fields: tuple[str, ...],
    schedule_index: int,
    chunk_size: int,
    size_class: SizeClass,
    header_row: tuple[str, ...] | None = None,
    worker_size: WorkerSize = "normal",
) -> FeedConfig:
    return FeedConfig(
        feed_name=feed_name,
        source_kind=source_kind,
        source_file_variant=source_file_variant,
        download_url=download_url,
        table_name=table_name,
        source_fields=source_fields,
        expected_field_count=len(source_fields),
        header_row=header_row,
        schedule_time_et=SCHEDULE_TIMES_ET[schedule_index],
        chunk_size=chunk_size,
        size_class=size_class,
        worker_size=worker_size,
    )


FEED_CATALOG: tuple[FeedConfig, ...] = (
    _feed(
        feed_name="AuthHist",
        source_kind="daily_diff_txt",
        source_file_variant="daily diff",
        download_url="https://data.transportation.gov/download/sn3k-dnx7/text%2Fplain",
        table_name="operating_authority_histories",
        source_fields=FMCSA_AUTHHIST_SOURCE_FIELDS,
        schedule_index=0,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="Revocation",
        source_kind="daily_diff_txt",
        source_file_variant="daily diff",
        download_url="https://data.transportation.gov/download/pivg-szje/text%2Fplain",
        table_name="operating_authority_revocations",
        source_fields=FMCSA_REVOCATION_SOURCE_FIELDS,
        schedule_index=1,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="Insurance",
        source_kind="daily_diff_txt",
        source_file_variant="daily diff",
        download_url="https://data.transportation.gov/download/mzmm-6xep/text%2Fplain",
        table_name="insurance_policies",
        source_fields=FMCSA_INSURANCE_SOURCE_FIELDS,
        schedule_index=2,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="ActPendInsur",
        source_kind="daily_diff_txt",
        source_file_variant="daily diff",
        download_url="https://data.transportation.gov/download/chgs-tx6x/text%2Fplain",
        table_name="insurance_policy_filings",
        source_fields=FMCSA_ACTPENDINSUR_SOURCE_FIELDS,
        schedule_index=3,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="InsHist",
        source_kind="daily_diff_txt",
        source_file_variant="daily diff",
        download_url="https://data.transportation.gov/download/xkmg-ff2t/text%2Fplain",
        table_name="insurance_policy_history_events",
        source_fields=FMCSA_INSHIST_SOURCE_FIELDS,
        schedule_index=4,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="Carrier",
        source_kind="snapshot_txt",
        source_file_variant="daily",
        download_url="https://data.transportation.gov/download/6qg9-x4f8/text%2Fplain",
        table_name="carrier_registrations",
        source_fields=FMCSA_CARRIER_SOURCE_FIELDS,
        schedule_index=5,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="Rejected",
        source_kind="snapshot_txt",
        source_file_variant="daily",
        download_url="https://data.transportation.gov/download/t3zq-c6n3/text%2Fplain",
        table_name="insurance_filing_rejections",
        source_fields=FMCSA_REJECTED_SOURCE_FIELDS,
        schedule_index=6,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="BOC3",
        source_kind="snapshot_txt",
        source_file_variant="daily",
        download_url="https://data.transportation.gov/download/fb8g-ngam/text%2Fplain",
        table_name="process_agent_filings",
        source_fields=FMCSA_BOC3_SOURCE_FIELDS,
        schedule_index=7,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="InsHist - All With History",
        source_kind="snapshot_txt",
        source_file_variant="all_with_history",
        download_url="https://data.transportation.gov/download/nzpz-e5xn/text%2Fplain",
        table_name="insurance_policy_history_events",
        source_fields=FMCSA_INSHIST_SOURCE_FIELDS,
        schedule_index=8,
        chunk_size=10_000,
        size_class="large",
        worker_size="xl",
    ),
    _feed(
        feed_name="BOC3 - All With History",
        source_kind="snapshot_txt",
        source_file_variant="all_with_history",
        download_url="https://data.transportation.gov/download/gmxu-awv7/text%2Fplain",
        table_name="process_agent_filings",
        source_fields=FMCSA_BOC3_SOURCE_FIELDS,
        schedule_index=9,
        chunk_size=10_000,
        size_class="medium",
    ),
    _feed(
        feed_name="ActPendInsur - All With History",
        source_kind="snapshot_txt",
        source_file_variant="all_with_history",
        download_url="https://data.transportation.gov/download/y77m-3nfx/text%2Fplain",
        table_name="insurance_policy_filings",
        source_fields=FMCSA_ACTPENDINSUR_SOURCE_FIELDS,
        schedule_index=10,
        chunk_size=10_000,
        size_class="medium",
    ),
    _feed(
        feed_name="Rejected - All With History",
        source_kind="snapshot_txt",
        source_file_variant="all_with_history",
        download_url="https://data.transportation.gov/download/9m5y-imtw/text%2Fplain",
        table_name="insurance_filing_rejections",
        source_fields=FMCSA_REJECTED_SOURCE_FIELDS,
        schedule_index=11,
        chunk_size=10_000,
        size_class="small",
    ),
    _feed(
        feed_name="AuthHist - All With History",
        source_kind="snapshot_txt",
        source_file_variant="all_with_history",
        download_url="https://data.transportation.gov/download/wahn-z3rq/text%2Fplain",
        table_name="operating_authority_histories",
        source_fields=FMCSA_AUTHHIST_SOURCE_FIELDS,
        schedule_index=12,
        chunk_size=10_000,
        size_class="large",
        worker_size="xl",
    ),
    _feed(
        feed_name="SMS AB PassProperty",
        source_kind="sms_csv",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/4y6x-dmck/rows.csv?accessType=DOWNLOAD",
        table_name="carrier_safety_basic_measures",
        source_fields=SMS_PASSPROPERTY_SOURCE_FIELDS,
        schedule_index=13,
        chunk_size=25_000,
        size_class="medium",
        header_row=SMS_PASSPROPERTY_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="SMS C PassProperty",
        source_kind="sms_csv",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/h9zy-gjn8/rows.csv?accessType=DOWNLOAD",
        table_name="carrier_safety_basic_measures",
        source_fields=SMS_PASSPROPERTY_SOURCE_FIELDS,
        schedule_index=14,
        chunk_size=25_000,
        size_class="medium",
        header_row=SMS_PASSPROPERTY_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="SMS Input - Violation",
        source_kind="sms_csv",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/8mt8-2mdr/rows.csv?accessType=DOWNLOAD",
        table_name="source_fmcsa_sms_input_violations",
        source_fields=SMS_INPUT_VIOLATION_SOURCE_FIELDS,
        schedule_index=15,
        chunk_size=50_000,
        size_class="large",
        header_row=SMS_INPUT_VIOLATION_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="SMS Input - Inspection",
        source_kind="sms_csv",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/rbkj-cgst/rows.csv?accessType=DOWNLOAD",
        table_name="carrier_inspections",
        source_fields=SMS_INPUT_INSPECTION_SOURCE_FIELDS,
        schedule_index=16,
        chunk_size=25_000,
        size_class="large",
        header_row=SMS_INPUT_INSPECTION_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="SMS Input - Motor Carrier Census",
        source_kind="sms_csv",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/kjg3-diqy/rows.csv?accessType=DOWNLOAD",
        table_name="motor_carrier_census_records",
        source_fields=SMS_MOTOR_CARRIER_CENSUS_SOURCE_FIELDS,
        schedule_index=17,
        chunk_size=25_000,
        size_class="large",
        header_row=SMS_MOTOR_CARRIER_CENSUS_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="SMS AB Pass",
        source_kind="sms_csv",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/m3ry-qcip/rows.csv?accessType=DOWNLOAD",
        table_name="carrier_safety_basic_percentiles",
        source_fields=SMS_PASS_SOURCE_FIELDS,
        schedule_index=18,
        chunk_size=25_000,
        size_class="small",
        header_row=SMS_PASS_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="SMS C Pass",
        source_kind="sms_csv",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/h3zn-uid9/rows.csv?accessType=DOWNLOAD",
        table_name="carrier_safety_basic_percentiles",
        source_fields=SMS_PASS_SOURCE_FIELDS,
        schedule_index=19,
        chunk_size=25_000,
        size_class="small",
        header_row=SMS_PASS_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="Crash File",
        source_kind="csv_export",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/aayw-vxb3/rows.csv?accessType=DOWNLOAD",
        table_name="commercial_vehicle_crashes",
        source_fields=FMCSA_CRASH_FILE_SOURCE_FIELDS,
        schedule_index=20,
        chunk_size=25_000,
        size_class="large",
        worker_size="xl",
        header_row=FMCSA_CRASH_FILE_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="Carrier - All With History",
        source_kind="csv_export",
        source_file_variant="all_with_history",
        download_url="https://data.transportation.gov/api/views/6eyk-hxee/rows.csv?accessType=DOWNLOAD",
        table_name="carrier_registrations",
        source_fields=FMCSA_CARRIER_SOURCE_FIELDS,
        schedule_index=21,
        chunk_size=25_000,
        size_class="large",
        header_row=FMCSA_CARRIER_ALL_HISTORY_HEADERS,
    ),
    _feed(
        feed_name="Inspections Per Unit",
        source_kind="csv_export",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/wt8s-2hbx/rows.csv?accessType=DOWNLOAD",
        table_name="vehicle_inspection_units",
        source_fields=FMCSA_INSPECTION_UNITS_SOURCE_FIELDS,
        schedule_index=22,
        chunk_size=50_000,
        size_class="large",
        header_row=FMCSA_INSPECTION_UNITS_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="Special Studies",
        source_kind="csv_export",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/5qik-smay/rows.csv?accessType=DOWNLOAD",
        table_name="vehicle_inspection_special_studies",
        source_fields=FMCSA_SPECIAL_STUDIES_SOURCE_FIELDS,
        schedule_index=23,
        chunk_size=10_000,
        size_class="medium",
        header_row=FMCSA_SPECIAL_STUDIES_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="Revocation - All With History",
        source_kind="csv_export",
        source_file_variant="all_with_history",
        download_url="https://data.transportation.gov/api/views/sa6p-acbp/rows.csv?accessType=DOWNLOAD",
        table_name="operating_authority_revocations",
        source_fields=FMCSA_REVOCATION_SOURCE_FIELDS,
        schedule_index=24,
        chunk_size=10_000,
        size_class="large",
        header_row=FMCSA_REVOCATION_ALL_HISTORY_HEADERS,
    ),
    _feed(
        feed_name="Insur - All With History",
        source_kind="csv_export",
        source_file_variant="all_with_history",
        download_url="https://data.transportation.gov/api/views/ypjt-5ydn/rows.csv?accessType=DOWNLOAD",
        table_name="insurance_policies",
        source_fields=FMCSA_INSURANCE_SOURCE_FIELDS,
        schedule_index=25,
        chunk_size=10_000,
        size_class="medium",
        header_row=FMCSA_INSUR_ALL_HISTORY_HEADERS,
    ),
    _feed(
        feed_name="OUT OF SERVICE ORDERS",
        source_kind="csv_export",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/p2mt-9ige/rows.csv?accessType=DOWNLOAD",
        table_name="out_of_service_orders",
        source_fields=FMCSA_OUT_OF_SERVICE_ORDER_SOURCE_FIELDS,
        schedule_index=26,
        chunk_size=10_000,
        size_class="medium",
        header_row=FMCSA_OUT_OF_SERVICE_ORDER_HEADERS,
    ),
    _feed(
        feed_name="Inspections and Citations",
        source_kind="csv_export",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/qbt8-7vic/rows.csv?accessType=DOWNLOAD",
        table_name="vehicle_inspection_citations",
        source_fields=FMCSA_INSPECTION_CITATIONS_SOURCE_FIELDS,
        schedule_index=27,
        chunk_size=10_000,
        size_class="small",
        header_row=FMCSA_INSPECTION_CITATIONS_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="Vehicle Inspections and Violations",
        source_kind="csv_export",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/876r-jsdb/rows.csv?accessType=DOWNLOAD",
        table_name="source_fmcsa_vehicle_inspection_violations",
        source_fields=FMCSA_VEHICLE_INSPECTION_VIOLATIONS_SOURCE_FIELDS,
        schedule_index=28,
        chunk_size=50_000,
        size_class="large",
        worker_size="xl",
        header_row=FMCSA_VEHICLE_INSPECTION_VIOLATIONS_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="Company Census File",
        source_kind="csv_export",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/az4n-8mr2/rows.csv?accessType=DOWNLOAD",
        table_name="motor_carrier_census_records",
        source_fields=FMCSA_COMPANY_CENSUS_SOURCE_FIELDS,
        schedule_index=29,
        chunk_size=10_000,
        size_class="large",
        worker_size="xl",
        header_row=FMCSA_COMPANY_CENSUS_SOURCE_FIELDS,
    ),
    _feed(
        feed_name="Vehicle Inspection File",
        source_kind="csv_export",
        source_file_variant="csv_export",
        download_url="https://data.transportation.gov/api/views/fx4q-ay7w/rows.csv?accessType=DOWNLOAD",
        table_name="carrier_inspections",
        source_fields=FMCSA_VEHICLE_INSPECTION_FILE_SOURCE_FIELDS,
        schedule_index=30,
        chunk_size=10_000,
        size_class="large",
        worker_size="xl",
        header_row=FMCSA_VEHICLE_INSPECTION_FILE_SOURCE_FIELDS,
    ),
)


FEED_BY_NAME = {feed.feed_name: feed for feed in FEED_CATALOG}
